/**
 * PriceX - Language Context Provider
 * Manages 12 languages with instant switching and RTL support
 */

'use client';

import React, { createContext, useContext, useState, useCallback, useEffect } from 'react';
import { Language, LanguageConfig, LANGUAGES } from '@/types';

interface LanguageContextType {
  currentLanguage: Language;
  currentLanguageConfig: LanguageConfig;
  setLanguage: (lang: Language) => void;
  availableLanguages: LanguageConfig[];
  isRTL: boolean;
  direction: 'ltr' | 'rtl';
  t: (key: string, fallback?: string) => string;
  isLoading: boolean;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const STORAGE_KEY = 'pricex-language-prefs';
const DEFAULT_LANGUAGE: Language = 'en';

// Translation dictionaries (comprehensive - all pages and components)
const translations: Record<Language, Record<string, string>> = {
  en: {
    // App
    'app.name': 'PriceX',
    'app.tagline': 'Global AI-Powered Price Comparison',
    'app.description': 'Find the best prices across millions of products from thousands of retailers worldwide.',
    
    // Navigation
    'nav.home': 'Home',
    'nav.search': 'Search',
    'nav.categories': 'Categories',
    'nav.deals': 'Hot Deals',
    'nav.alerts': 'Price Alerts',
    'nav.account': 'My Account',
    'nav.compare': 'Compare',
    'nav.cashback': 'Cashback',
    'nav.login': 'Login',
    'nav.register': 'Sign Up',
    'nav.logout': 'Logout',
    'nav.admin': 'Admin',
    
    // Search
    'search.placeholder': 'Search products, brands, or categories...',
    'search.button': 'Search',
    'search.searching': 'Searching...',
    'search.results': 'Results',
    'search.resultsFor': 'results for',
    'search.didYouMean': 'Did you mean',
    'search.noResults': 'No products found',
    'search.noResultsDesc': 'Try adjusting your search or filters',
    'search.tryAgain': 'Try again',
    'search.filter': 'Filter',
    'search.filters': 'Filters',
    'search.sort': 'Sort by',
    'search.sortRelevance': 'Relevance',
    'search.sortPriceLow': 'Price: Low to High',
    'search.sortPriceHigh': 'Price: High to Low',
    'search.sortRating': 'Highest Rated',
    'search.sortNewest': 'Newest',
    'search.priceRange': 'Price Range',
    'search.categories': 'Categories',
    'search.brands': 'Brands',
    'search.minRating': 'Minimum Rating',
    'search.stars': 'stars',
    'search.clearFilters': 'Clear all filters',
    'search.aiSuggestions': 'AI Suggestions',
    'search.previous': 'Previous',
    'search.next': 'Next',
    'search.under': 'Under',
    'search.over': 'Over',
    
    // Region & Currency & Language
    'region.select': 'Select Region',
    'region.current': 'Current Region',
    'country.select': 'Select Country',
    'language.select': 'Select Language',
    'currency.select': 'Select Currency',
    'currency.rates': 'Exchange Rates',
    'currency.lastUpdated': 'Last updated',
    
    // Product
    'product.compare': 'Compare Prices',
    'product.priceHistory': 'Price History',
    'product.alert': 'Set Alert',
    'product.buyNow': 'Buy Now',
    'product.viewDeal': 'View Deal',
    'product.addToCompare': 'Add to Compare',
    'product.removeFromCompare': 'Remove from Compare',
    'product.bestPrice': 'Best Price',
    'product.lowestPrice': 'Lowest Price',
    'product.highestPrice': 'Highest Price',
    'product.originalPrice': 'Original Price',
    'product.discount': 'Discount',
    'product.inStock': 'In Stock',
    'product.outOfStock': 'Out of Stock',
    'product.freeShipping': 'Free Shipping',
    'product.official': 'Official Store',
    'product.from': 'from',
    'product.retailer': 'Retailer',
    'product.specifications': 'Specifications',
    'product.features': 'Features',
    'product.reviews': 'Reviews',
    'product.rating': 'Rating',
    'product.sku': 'SKU',
    'product.noImage': 'No image',
    'product.noImageAvailable': 'No image available',
    'product.alertMe': 'Alert me',
    'product.viewDeal': 'View Deal',
    'product.backInStockAlert': 'Back in Stock Alert',
    'product.locations': 'locations',
    'product.brand': 'Brand',
    'product.model': 'Model',
    'product.category': 'Category',
    'product.description': 'Description',
    'product.warranty': 'Warranty',
    'product.shipping': 'Shipping',
    'product.availability': 'Availability',
    'product.addToCart': 'Add to Cart',
    'product.reviews': 'reviews',
    'product.setAlert': 'Set Price Alert',
    'product.viewAll': 'View All',
    'product.similar': 'Similar Products',
    
    // Price Alerts
    'alerts.title': 'Price Alerts',
    'alerts.subtitle': 'Get notified when prices drop',
    'alerts.create': 'Create Alert',
    'alerts.targetPrice': 'Target Price',
    'alerts.currentPrice': 'Current Price',
    'alerts.priceDrop': 'Price Drop',
    'alerts.delete': 'Delete',
    'alerts.edit': 'Edit',
    'alerts.noAlerts': 'No price alerts yet',
    'alerts.createFirst': 'Create your first price alert',
    'alerts.backInStock': 'Back in Stock',
    'alerts.setAlert': 'Set Alert',
    'alerts.alertSet': 'Alert Set!',
    'alerts.totalAlerts': 'Total Alerts',
    'alerts.priceDrops': 'Price Drops',
    'alerts.howItWorks': 'How Price Alerts Work',
    'alerts.setTarget': 'Set Your Target Price',
    'alerts.setTargetDesc': 'Choose the price you want to pay',
    'alerts.weMonitor': 'We Monitor Prices',
    'alerts.weMonitorDesc': 'Our AI tracks prices 24/7',
    'alerts.getNotified': 'Get Instant Notifications',
    'alerts.getNotifiedDesc': 'Get notified when prices drop',
    
    // Deals
    'deals.title': 'Hot Deals',
    'deals.subtitle': 'Best prices today',
    'deals.all': 'All Deals',
    'deals.ending': 'Ending Soon',
    'deals.new': 'New',
    'deals.popular': 'Popular',
    'deals.noDeals': 'No deals found',
    'deals.checkBack': 'Check back later for new deals',
    'deals.biggestDiscount': 'Biggest Discount',
    'deals.priceLowHigh': 'Price: Low to High',
    'deals.priceHighLow': 'Price: High to Low',
    'deals.highestRated': 'Highest Rated',
    'deals.lowestGuarantee': 'Lowest Price Guarantee',
    'deals.lowestGuaranteeDesc': 'We match any lower price',
    'deals.flashDeals': 'Flash Deals',
    'deals.flashDealsDesc': 'Limited time offers',
    'deals.priceDrops': 'Price Drops',
    'deals.priceDropsDesc': 'Track price history',
    
    // Compare
    'compare.title': 'Compare Products',
    'compare.subtitle': 'Compare prices and features',
    'compare.addProduct': 'Add Product',
    'compare.addProductDesc': 'Add products to your comparison list to see side-by-side comparisons of prices, features, and specifications.',
    'compare.noProducts': 'No products to compare',
    'compare.maxProducts': 'Maximum 4 products can be compared',
    'compare.clearAll': 'Clear all',
    'compare.back': 'Back',
    'compare.products': 'products',
    'compare.bestDealHighlighted': 'with best deal highlighted in green',
    'compare.startComparing': 'Start Comparing',
    'compare.tips': 'Comparison Tips',
    'compare.bestDeal': 'Best Deal Highlighted',
    'compare.bestDealDesc': 'The lowest price is automatically highlighted in green for easy identification.',
    'compare.storeLocations': 'Store Locations',
    'compare.storeLocationsDesc': 'Check store locations to find the nearest pickup point or delivery option.',
    'compare.skuGrouping': 'SKU Grouping',
    'compare.skuGroupingDesc': 'Identical products with the same SKU from different stores are grouped together.',
    'compare.currencyConversion': 'Currency Conversion',
    'compare.currencyConversionDesc': 'Prices are displayed in your selected currency with real-time FX rates.',
    
    // Categories
    'categories.title': 'Categories',
    'categories.subtitle': 'Browse by category',
    'categories.electronics': 'Electronics & Gadgets',
    'categories.homeAppliances': 'Home Appliances & Kitchenware',
    'categories.fashion': 'Fashion & Apparel',
    'categories.beauty': 'Beauty & Personal Care',
    'categories.groceries': 'Groceries & Food & Beverages',
    'categories.automotive': 'Automotive & Car Accessories',
    'categories.health': 'Health, Fitness & Supplements',
    'categories.baby': 'Baby, Kids & Toys',
    'categories.office': 'Office, Industrial & Stationery',
    'categories.sports': 'Sports & Outdoors',
    'categories.books': 'Books, Music & Movies',
    'categories.pets': 'Pet Supplies',
    'categories.garden': 'Garden, DIY & Tools',
    'categories.travel': 'Travel & Luggage',
    'categories.luxury': 'Luxury, Jewelry & Watches',
    'categories.software': 'Software & Digital Goods',
    'categories.furniture': 'Furniture & Home Decor',
    'categories.pharmacy': 'Pharmaceuticals & OTC',
    'categories.newArrivals': 'Newly Added Categories',
    'categories.art': 'Art & Collectibles',
    'categories.music': 'Musical Instruments',
    'categories.industrial': 'Industrial Equipment',
    'categories.smartHome': 'Smart Home / IoT',
    'categories.digital': 'Digital Goods & Subscriptions',
    'categories.finance': 'Finance & Insurance',
    'categories.eco': 'Green / Eco Products',
    
    // Cashback
    'cashback.title': 'Cashback & Rewards',
    'cashback.subtitle': 'Earn money back on your purchases',
    'cashback.earn': 'Earn Money Back on Every Purchase',
    'cashback.heroTitle': 'Get Paid to Shop with PriceX Cashback',
    'cashback.heroDesc': 'Activate cashback at 10,000+ stores and earn up to 40% back on every purchase. Its free money - why leave it on the table?',
    'cashback.startEarning': 'Start Earning',
    'cashback.howItWorks': 'How It Works',
    'cashback.topStores': 'Top Cashback Stores',
    'cashback.activate': 'Activate',
    'cashback.cashback': 'cashback',
    'cashback.viewAll': 'View All Stores',
    'cashback.howItWorksTitle': 'How PriceX Cashback Works',
    'cashback.step1': 'Activate Cashback',
    'cashback.step1Desc': 'Browse deals and activate cashback before shopping',
    'cashback.step2': 'Shop Normally',
    'cashback.step2Desc': 'Make your purchase as usual on the retailer site',
    'cashback.step3': 'Earn Rewards',
    'cashback.step3Desc': 'Get cashback credited to your account within 24 hours',
    'cashback.step4': 'Get Paid',
    'cashback.step4Desc': 'Withdraw via PayPal, gift card, or donate to charity',
    'cashback.features.shopSafely': 'Shop Safely',
    'cashback.features.shopSafelyDesc': 'All purchases are protected. If cashback doesnt track, well refund you.',
    'cashback.features.fastPayouts': 'Fast Payouts',
    'cashback.features.fastPayoutsDesc': 'Cashback posts within 24 hours. Withdraw anytime via PayPal or gift card.',
    'cashback.features.stackRewards': 'Stack Rewards',
    'cashback.features.stackRewardsDesc': 'Combine with credit card points, coupon codes, and loyalty programs for maximum savings.',
    'cashback.stats.cashbackPaid': 'Cashback Paid',
    'cashback.stats.partnerStores': 'Partner Stores',
    'cashback.stats.members': 'Members',
    'cashback.stats.highestCashback': 'Highest Cashback',
    'cashback.available': 'Available',
    'cashback.pending': 'Pending',
    'cashback.redeemed': 'Redeemed',
    
    // Auth
    'auth.login': 'Login',
    'auth.register': 'Register',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.confirmPassword': 'Confirm Password',
    'auth.name': 'Name',
    'auth.forgotPassword': 'Forgot Password?',
    'auth.google': 'Google',
    'auth.apple': 'Apple',
    'auth.noAccount': "Don't have an account?",
    'auth.hasAccount': 'Already have an account?',
    'auth.loginSuccess': 'Login successful',
    'auth.registerSuccess': 'Registration successful',
    'auth.error': 'Authentication error',
    'auth.welcomeBack': 'Welcome Back',
    'auth.signInDesc': 'Sign in to access your saved products and alerts',
    'auth.fillAllFields': 'Please fill in all fields',
    'auth.loginFailed': 'Login failed',
    'auth.emailPlaceholder': 'Enter your email',
    'auth.passwordPlaceholder': 'Enter your password',
    'auth.rememberMe': 'Remember me',
    'auth.signingIn': 'Signing in...',
    'auth.createOne': 'Create one',
    'auth.continueWith': 'Or continue with',
    'auth.createAccount': 'Create Account',
    'auth.registerDesc': 'Join PriceX and start saving',
    'auth.fillAllFields': 'Please fill in all fields',
    'auth.passwordsNotMatch': 'Passwords do not match',
    'auth.agreeTerms': 'Please agree to the terms and conditions',
    'auth.registerFailed': 'Registration failed',
    'auth.namePlaceholder': 'Enter your full name',
    'auth.confirmPasswordPlaceholder': 'Confirm your password',
    'auth.agreeTermsText': 'I agree to the',
    'auth.creating': 'Creating account...',
    'auth.atLeast8': 'At least 8 characters',
    'auth.oneUppercase': 'One uppercase letter',
    'auth.oneNumber': 'One number',
    'auth.oneSpecial': 'One special character',
    
    // Home Page
    'home.hero.title': 'Find the Best Prices',
    'home.hero.subtitle': 'Compare millions of products from thousands of retailers worldwide',
    'home.features.title': 'Why Choose PriceX',
    'home.features.aiSearch': 'AI-Powered Search',
    'home.features.aiSearchDesc': 'Smart product matching across millions of items from thousands of retailers worldwide.',
    'home.features.priceHistory': 'Price History',
    'home.features.priceHistoryDesc': 'Track price trends over time and identify the best moment to buy.',
    'home.features.smartAlerts': 'Smart Alerts',
    'home.features.smartAlertsDesc': 'Get notified instantly when prices drop to your target level.',
    'home.features.trustedReviews': 'Trusted Reviews',
    'home.features.trustedReviewsDesc': 'Verified user reviews and ratings to help you make informed decisions.',
    'home.features.realTime': 'Real-Time Updates',
    'home.features.realTimeDesc': 'Live price tracking with updates every few minutes.',
    'home.features.global': 'Global Coverage',
    'home.features.globalDesc': 'Compare prices across 8 regions and 18 currencies instantly.',
    'home.stats.users': 'Active Users',
    'home.stats.products': 'Products Tracked',
    'home.stats.retailers': 'Retailers',
    'home.stats.countries': 'Countries',
    'home.categories.title': 'Popular Categories',
    'home.categories.viewAll': 'View All Categories',
    'home.pricing.title': 'Premium Plans',
    'home.pricing.subtitle': 'Unlock advanced features',
    
    // Pricing
    'pricing.title': 'Choose Your Plan from',
    'pricing.plan': 'Plan',
    'pricing.monthly': 'Monthly',
    'pricing.yearly': 'Yearly',
    'pricing.save': 'Save',
    'pricing.mostPopular': 'Most Popular',
    'pricing.billedAnnually': 'month (billed annually)',
    'pricing.perMonth': 'month',
    'pricing.getStarted': 'Get Started',
    'pricing.subscribe': 'Subscribe Now',
    'pricing.moneyBack': '30-day money back guarantee',
    'pricing.cancel': 'Cancel anytime',
    'pricing.usersTrust': '10M+ users trust PriceX',
    
    // Free Plan
    'pricing.free.name': 'Free',
    'pricing.free.period': 'forever',
    'pricing.free.description': 'Basic price tracking for casual shoppers',
    'pricing.free.feature1': 'Price comparisons for 1,000 products',
    'pricing.free.feature2': '5 price alerts',
    'pricing.free.feature3': 'Basic deal scores',
    'pricing.free.feature4': 'Web access only',
    'pricing.free.feature5': 'English language',
    
    // Premium Plan
    'pricing.premium.name': 'Premium',
    'pricing.premium.period': 'month',
    'pricing.premium.description': 'For serious savers who want the best deals',
    'pricing.premium.feature1': 'Unlimited product comparisons',
    'pricing.premium.feature2': 'Unlimited price alerts',
    'pricing.premium.feature3': 'Advanced deal scores with AI predictions',
    'pricing.premium.feature4': 'Price history charts (365 days)',
    'pricing.premium.feature5': 'Cashback rewards activation',
    'pricing.premium.feature6': 'Voice search',
    'pricing.premium.feature7': 'All 12 languages',
    'pricing.premium.feature8': 'Ad-free experience',
    'pricing.premium.feature9': 'Priority customer support',
    
    // Pro Plan
    'pricing.pro.name': 'Pro',
    'pricing.pro.period': 'month',
    'pricing.pro.description': 'For power users and small businesses',
    'pricing.pro.feature1': 'Everything in Premium',
    'pricing.pro.feature2': 'API access (1,000 calls/month)',
    'pricing.pro.feature3': 'Custom price dashboards',
    'pricing.pro.feature4': 'Export data to CSV/Excel',
    'pricing.pro.feature5': 'Bulk product tracking',
    'pricing.pro.feature6': 'Team collaboration (up to 5)',
    'pricing.pro.feature7': 'Custom alerts (SMS, WhatsApp)',
    'pricing.pro.feature8': 'White-label reports',
    'pricing.pro.feature9': 'Dedicated account manager',
    
    // Enterprise Plan
    'pricing.enterprise.name': 'Enterprise',
    'pricing.enterprise.period': 'month',
    'pricing.enterprise.description': 'For large organizations with advanced needs',
    'pricing.enterprise.feature1': 'Everything in Pro',
    'pricing.enterprise.feature2': 'Unlimited API access',
    'pricing.enterprise.feature3': 'Custom integrations',
    'pricing.enterprise.feature4': 'Real-time data feeds',
    'pricing.enterprise.feature5': 'Advanced analytics',
    'pricing.enterprise.feature6': 'Dedicated infrastructure',
    'pricing.enterprise.feature7': 'Custom SLA',
    'pricing.enterprise.feature8': 'On-premise deployment option',
    'pricing.enterprise.feature9': 'Volume discounts',
    
    // Footer
    'footer.about': 'About PriceX',
    'footer.contact': 'Contact Us',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms of Service',
    'footer.help': 'Help Center',
    'footer.careers': 'Careers',
    'footer.newsletter': 'Newsletter',
    'footer.newsletterText': 'Subscribe to get the latest deals',
    'footer.subscribe': 'Subscribe',
    'footer.email': 'Enter your email',
    'footer.copyright': '© 2024 PriceX. All rights reserved.',
    'footer.followUs': 'Follow Us',
    'footer.company': 'Company',
    'footer.support': 'Support',
    'footer.legal': 'Legal',
    'footer.partners': 'Partners',
    'footer.press': 'Press',
    'footer.blog': 'Blog',
    'footer.faqs': 'FAQs',
    'footer.feedback': 'Feedback',
    'footer.cookies': 'Cookie Policy',
    'footer.accessibility': 'Accessibility',
    'footer.retailers': 'For Retailers',
    'footer.brands': 'For Brands',
    'footer.advertise': 'Advertise',
    'footer.apiAccess': 'API Access',
    'footer.stayUpdated': 'Stay Updated',
    
    // Common
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.retry': 'Retry',
    'common.cancel': 'Cancel',
    'common.save': 'Save',
    'common.close': 'Close',
    'common.seeAll': 'See All',
    'common.viewAll': 'View All',
    'common.learnMore': 'Learn More',
    'common.getStarted': 'Get Started',
    'common.continue': 'Continue',
    'common.back': 'Back',
    'common.next': 'Next',
    'common.done': 'Done',
    'common.today': 'Today',
    'common.yesterday': 'Yesterday',
    'common.thisWeek': 'This Week',
    'common.thisMonth': 'This Month',
    'common.all': 'All',
    'common.none': 'None',
    'common.or': 'or',
    'common.and': 'and',
    'common.theme': 'Theme',
    'common.light': 'Light',
    'common.dark': 'Dark',
    'common.auto': 'Auto',
    
    // Admin
    'admin.dashboard': 'Dashboard',
    'admin.users': 'Users',
    'admin.products': 'Products',
    'admin.orders': 'Orders',
    'admin.settings': 'Settings',
    
    // Error & Success
    'error.general': 'Something went wrong',
    'error.network': 'Network error',
    'error.notFound': 'Not found',
    'success.saved': 'Saved successfully',
    'success.deleted': 'Deleted successfully',
  },
  ar: {
    'app.name': 'PriceX',
    'app.tagline': 'منصة المقارنة العالمية للأسعار بالذكاء الاصطناعي',
    'app.description': 'اعثر على أفضل الأسعار عبر ملايين المنتجات من آلاف التجار حول العالم.',
    'nav.home': 'الرئيسية',
    'nav.search': 'بحث',
    'nav.categories': 'الفئات',
    'nav.deals': 'عروض ساخنة',
    'nav.alerts': 'تنبيهات الأسعار',
    'nav.account': 'حسابي',
    'nav.compare': 'مقارنة',
    'nav.cashback': 'استرداد نقدي',
    'nav.login': 'تسجيل الدخول',
    'nav.register': 'سجل الآن',
    'nav.logout': 'تسجيل الخروج',
    'nav.admin': 'إدارة',
    'search.placeholder': 'ابحث عن منتجات أو علامات تجارية أو فئات...',
    'search.button': 'بحث',
    'search.searching': 'جاري البحث...',
    'search.results': 'النتائج',
    'search.resultsFor': 'نتيجة لـ',
    'search.didYouMean': 'هل تقصد',
    'search.noResults': 'لم يتم العثور على منتجات',
    'search.noResultsDesc': 'حاول تعديل البحث أو الفلاتر',
    'search.tryAgain': 'حاول مجدداً',
    'search.filter': 'تصفية',
    'search.filters': 'الفلاتر',
    'search.sort': 'ترتيب حسب',
    'search.sortRelevance': 'الملاءمة',
    'search.sortPriceLow': 'السعر: من الأقل للأعلى',
    'search.sortPriceHigh': 'السعر: من الأعلى للأقل',
    'search.sortRating': 'الأعلى تقييماً',
    'search.sortNewest': 'الأحدث',
    'search.priceRange': 'نطاق السعر',
    'search.categories': 'الفئات',
    'search.brands': 'العلامات التجارية',
    'search.minRating': 'الحد الأدنى للتقييم',
    'search.stars': 'نجوم',
    'search.clearFilters': 'مسح جميع الفلاتر',
    'search.aiSuggestions': 'اقتراحات الذكاء الاصطناعي',
    'search.previous': 'السابق',
    'search.next': 'التالي',
    'search.under': 'أقل من',
    'search.over': 'أكثر من',
    'region.select': 'اختر المنطقة',
    'region.current': 'المنطقة الحالية',
    'country.select': 'اختر الدولة',
    'language.select': 'اختر اللغة',
    'currency.select': 'اختر العملة',
    'currency.rates': 'أسعار الصرف',
    'currency.lastUpdated': 'آخر تحديث',
    'product.compare': 'قارن الأسعار',
    'product.priceHistory': 'تاريخ الأسعار',
    'product.alert': 'تعيين تنبيه',
    'product.buyNow': 'اشتر الآن',
    'product.viewDeal': 'عرض العرض',
    'product.addToCompare': 'إضافة للمقارنة',
    'product.removeFromCompare': 'إزالة من المقارنة',
    'product.bestPrice': 'أفضل سعر',
    'product.lowestPrice': 'أقل سعر',
    'product.highestPrice': 'أعلى سعر',
    'product.originalPrice': 'السعر الأصلي',
    'product.discount': 'الخصم',
    'product.inStock': 'متوفر',
    'product.outOfStock': 'غير متوفر',
    'product.freeShipping': 'شحن مجاني',
    'product.official': 'متجر رسمي',
    'product.from': 'من',
    'product.retailer': 'التاجر',
    'product.specifications': 'المواصفات',
    'product.features': 'المميزات',
    'product.reviews': 'التقييمات',
    'product.rating': 'التقييم',
    'product.sku': 'رمز المنتج',
    'product.noImage': 'لا توجد صورة',
    'product.noImageAvailable': 'لا توجد صورة متاحة',
    'product.alertMe': 'أبلغني',
    'product.viewDeal': 'عرض الصفقة',
    'product.backInStockAlert': 'تنبيه عند التوفر',
    'product.locations': 'مواقع',
    'product.brand': 'العلامة التجارية',
    'product.model': 'الموديل',
    'product.category': 'الفئة',
    'product.description': 'الوصف',
    'product.warranty': 'الضمان',
    'product.shipping': 'الشحن',
    'product.availability': 'التوفر',
    'product.addToCart': 'إضافة للسلة',
    'product.reviews': 'تقييم',
    'product.setAlert': 'تعيين تنبيه سعر',
    'product.viewAll': 'عرض الكل',
    'product.similar': 'منتجات مشابهة',
    'alerts.title': 'تنبيهات الأسعار',
    'alerts.subtitle': 'احصل على إشعار عند انخفاض الأسعار',
    'alerts.create': 'إنشاء تنبيه',
    'alerts.targetPrice': 'السعر المستهدف',
    'alerts.currentPrice': 'السعر الحالي',
    'alerts.priceDrop': 'انخفاض السعر',
    'alerts.delete': 'حذف',
    'alerts.edit': 'تعديل',
    'alerts.noAlerts': 'لا توجد تنبيهات أسعار بعد',
    'alerts.createFirst': 'أنشئ تنبيه السعر الأول',
    'alerts.backInStock': 'متوفر مجدداً',
    'alerts.setAlert': 'تعيين تنبيه',
    'alerts.alertSet': 'تم تعيين التنبيه!',
    'deals.title': 'عروض ساخنة',
    'deals.subtitle': 'أفضل الأسعار اليوم',
    'deals.all': 'كل العروض',
    'deals.ending': 'ينتهي قريباً',
    'deals.new': 'جديد',
    'deals.popular': 'شائع',
    'compare.title': 'مقارنة المنتجات',
    'compare.subtitle': 'قارن الأسعار والميزات',
    'compare.addProduct': 'إضافة منتج',
    'compare.addProductDesc': 'أضف المنتجات إلى قائمة المقارنة لمقارنة الأسعار والميزات والمواصفات جنباً إلى جنب.',
    'compare.noProducts': 'لا توجد منتجات للمقارنة',
    'compare.maxProducts': 'الحد الأقصى 4 منتجات للمقارنة',
    'compare.clearAll': 'مسح الكل',
    'compare.back': 'رجوع',
    'compare.products': 'منتجات',
    'compare.bestDealHighlighted': 'مع أفضل صفقة مميزة بالأخضر',
    'compare.startComparing': 'ابدأ المقارنة',
    'compare.tips': 'نصائح المقارنة',
    'compare.bestDeal': 'أفضل صفقة',
    'compare.bestDealDesc': 'يتم تمييز أقل سعر تلقائياً بالأخضر لسهولة التعرف عليه.',
    'compare.storeLocations': 'مواقع المتاجر',
    'compare.storeLocationsDesc': 'تحقق من مواقع المتاجر للعثور على أقرب نقطة استلام أو خيار توصيل.',
    'compare.skuGrouping': 'تجميع SKU',
    'compare.skuGroupingDesc': 'المنتجات المتطابقة مع نفس SKU من متاجر مختلفة يتم تجميعها معاً.',
    'compare.currencyConversion': 'تحويل العملات',
    'compare.currencyConversionDesc': 'الأسعار معروضة بالعملة المختارة مع أسعار صرف فورية.',
    'categories.title': 'الفئات',
    'categories.subtitle': 'تصفح حسب الفئة',
    'categories.electronics': 'الإلكترونيات والأجهزة',
    'categories.homeAppliances': 'أجهزة منزلية ومطبخ',
    'categories.fashion': 'موضة وملابس',
    'categories.beauty': 'جمال وعناية شخصية',
    'categories.groceries': 'بقالة وطعام ومشروبات',
    'categories.automotive': 'سيارات وإكسسوارات',
    'categories.health': 'صحة ولياقة ومكملات',
    'categories.baby': 'أطفال وألعاب',
    'categories.office': 'مكتب وصناعة وقرطاسية',
    'categories.sports': 'رياضة خارجية',
    'categories.books': 'كتب وموسيقى وأفلام',
    'categories.pets': 'مستلزمات حيوانات أليفة',
    'categories.garden': 'حديقة وأدوات',
    'categories.travel': 'سفر وحقائب',
    'categories.luxury': 'مجوهرات وساعات فاخرة',
    'categories.software': 'برمجيات ورقمية',
    'categories.furniture': 'أثاث وديكور',
    'categories.pharmacy': 'صيدلية وأدوية',
    'categories.newArrivals': 'فئات مضافة حديثاً',
    'categories.art': 'فنون ومقتنيات',
    'categories.music': 'آلات موسيقية',
    'categories.industrial': 'معدات صناعية',
    'categories.smartHome': 'منزل ذكي',
    'categories.digital': 'سلع رقمية واشتراكات',
    'categories.finance': 'تموين وتأمين',
    'categories.eco': 'منتجات صديقة للبيئة',
    'cashback.title': 'استرداد نقدي ومكافآت',
    'cashback.subtitle': 'اربح المال على مشترياتك',
    'cashback.earn': 'اربح المال على كل عملية شراء',
    'cashback.heroTitle': 'احصل على المال للتسوق مع استرداد PriceX',
    'cashback.heroDesc': 'فعّل الاسترداد النقدي في أكثر من 10,000 متجر واربح حتى 40% على كل عملية شراء. إنه مال مجاني - لماذا تتركه على الطاولة؟',
    'cashback.startEarning': 'ابدأ الربح',
    'cashback.howItWorks': 'كيف يعمل',
    'cashback.topStores': 'أفضل متاجر الاسترداد النقدي',
    'cashback.activate': 'تفعيل',
    'cashback.cashback': 'استرداد نقدي',
    'cashback.viewAll': 'عرض جميع المتاجر',
    'cashback.howItWorksTitle': 'كيف يعمل استرداد PriceX',
    'cashback.step1': 'تفعيل الاسترداد',
    'cashback.step1Desc': 'تصفح العروض وفعّل الاسترداد قبل التسوق',
    'cashback.step2': 'تسوق كالمعتاد',
    'cashback.step2Desc': 'قم بعملية الشراء كما هو معتاد على موقع المتجر',
    'cashback.step3': 'اربح المكافآت',
    'cashback.step3Desc': 'احصل على الاسترداد النقدي في حسابك خلال 24 ساعة',
    'cashback.step4': 'احصل على أموالك',
    'cashback.step4Desc': 'اسحب عبر PayPal أو بطاقة الهدايا أوتبرع لل charity',
    'cashback.features.shopSafely': 'تسوق بأمان',
    'cashback.features.shopSafelyDesc': 'جميع المشتريات محمية. إذا لم يتم تتبع الاسترداد، سنقوم برد المبلغ.',
    'cashback.features.fastPayouts': 'مدفوعات سريعة',
    'cashback.features.fastPayoutsDesc': 'يضاف الاسترداد خلال 24 ساعة. اسحب في أي وقت عبر PayPal أو بطاقة الهدايا.',
    'cashback.features.stackRewards': '叠加 مكافآت',
    'cashback.features.stackRewardsDesc': 'اجمع بين نقاط بطاقات الائتمان ورموز الخصم وبرامج الولاء لتحقيق أقصى وفورات.',
    'cashback.stats.cashbackPaid': 'الاسترداد المدفوع',
    'cashback.stats.partnerStores': 'متاجر شريكة',
    'cashback.stats.members': 'أعضاء',
    'cashback.stats.highestCashback': 'أعلى استرداد',
    'cashback.available': 'متاح',
    'cashback.pending': 'قيد الانتظار',
    'cashback.redeemed': 'تم الاستبدال',
    'auth.login': 'تسجيل الدخول',
    'auth.register': 'تسجيل',
    'auth.email': 'البريد الإلكتروني',
    'auth.password': 'كلمة المرور',
    'auth.confirmPassword': 'تأكيد كلمة المرور',
    'auth.name': 'الاسم',
    'auth.forgotPassword': 'هل نسيت كلمة المرور؟',
    'auth.google': 'جوجل',
    'auth.apple': 'أبل',
    'auth.noAccount': 'ليس لديك حساب؟',
    'auth.hasAccount': 'لديك حساب بالفعل؟',
    'auth.loginSuccess': 'تم تسجيل الدخول بنجاح',
    'auth.registerSuccess': 'تم التسجيل بنجاح',
    'auth.error': 'خطأ في المصادقة',
    'home.hero.title': 'اعثر على أفضل الأسعار',
    'home.hero.subtitle': 'قارن ملايين المنتجات من آلاف التجار حول العالم',
    'home.features.title': 'لماذا تختار PriceX',
    'home.features.aiSearch': 'البحث بالذكاء الاصطناعي',
    'home.features.aiSearchDesc': 'مطابقة ذكية للمنتجات عبر ملايين المنتجات من آلاف التجار حول العالم.',
    'home.features.priceHistory': 'تاريخ الأسعار',
    'home.features.priceHistoryDesc': 'تتبع اتجاهات الأسعار وحدد أفضل لحظة للشراء.',
    'home.features.smartAlerts': 'تنبيهات ذكية',
    'home.features.smartAlertsDesc': 'احصل على إشعار فوري عندما تنخفض الأسعار.',
    'home.features.trustedReviews': 'تقييمات موثوقة',
    'home.features.trustedReviewsDesc': 'تقييمات ومراجعات المستخدمين لمساعدتك في اتخاذ قرارات مدروسة.',
    'home.features.realTime': 'تحديثات فورية',
    'home.features.realTimeDesc': 'تتبع الأسعار المباشر مع تحديثات كل بضع دقائق.',
    'home.features.global': 'تغطية عالمية',
    'home.features.globalDesc': 'قارن الأسعار عبر 8 مناطق و18 عملة فوراً.',
    'home.stats.users': 'المستخدمون النشطون',
    'home.stats.products': 'المنتجات المتتبعة',
    'home.stats.retailers': 'التجار',
    'home.stats.countries': 'الدول',
    'home.categories.title': 'الفئات الشائعة',
    'home.categories.viewAll': 'عرض جميع الفئات',
    'home.pricing.title': 'الخطط المميزة',
    'home.pricing.subtitle': 'فتح الميزات المتقدمة',
    'pricing.title': 'اختر خطتك من',
    'pricing.plan': 'الخطة',
    'pricing.monthly': 'شهري',
    'pricing.yearly': 'سنوي',
    'pricing.save': 'وفر',
    'pricing.mostPopular': 'الأكثر شعبية',
    'pricing.billedAnnually': 'شهر (فاتورة سنوية)',
    'pricing.perMonth': 'شهر',
    'pricing.getStarted': 'ابدأ الآن',
    'pricing.subscribe': 'اشترك الآن',
    'pricing.moneyBack': 'ضمان استرداد 30 يوم',
    'pricing.cancel': 'إلغاء في أي وقت',
    'pricing.usersTrust': '+10M مستخدم يثق في PriceX',
    'pricing.free.name': 'مجاني',
    'pricing.free.period': 'للأبد',
    'pricing.free.description': 'تتبع الأسعار الأساسي للمتسوقين العاديين',
    'pricing.free.feature1': 'مقارنات أسعار لـ 1,000 منتج',
    'pricing.free.feature2': '5 تنبيهات أسعار',
    'pricing.free.feature3': 'نتائج صفقات أساسية',
    'pricing.free.feature4': 'الوصول للويب فقط',
    'pricing.free.feature5': 'اللغة الإنجليزية',
    'pricing.premium.name': 'بريميوم',
    'pricing.premium.period': 'شهر',
    'pricing.premium.description': 'للموفرين الجاديين الذين يريدون أفضل الصفقات',
    'pricing.premium.feature1': 'مقارنات منتجات غير محدودة',
    'pricing.premium.feature2': 'تنبيهات أسعار غير محدودة',
    'pricing.premium.feature3': 'نتائج صفقات متقدمة مع تنبؤات AI',
    'pricing.premium.feature4': 'رسوم بيانية لتاريخ الأسعار (365 يوم)',
    'pricing.premium.feature5': 'تفعيل مكافآت الاسترداد النقدي',
    'pricing.premium.feature6': 'بحث صوتي',
    'pricing.premium.feature7': 'كل 12 لغة',
    'pricing.premium.feature8': 'تجربة بدون إعلانات',
    'pricing.premium.feature9': 'دعم عملاء أولوية',
    'pricing.pro.name': 'برو',
    'pricing.pro.period': 'شهر',
    'pricing.pro.description': 'للمستخدمين المتقدمين والأعمال الصغيرة',
    'pricing.pro.feature1': 'كل شيء في البريميوم',
    'pricing.pro.feature2': 'وصول API (1,000 طلب/شهر)',
    'pricing.pro.feature3': 'لوحات أسعار مخصصة',
    'pricing.pro.feature4': 'تصدير بيانات CSV/Excel',
    'pricing.pro.feature5': 'تتبع منتجات بالجملة',
    'pricing.pro.feature6': 'تعاون الفريق (حتى 5)',
    'pricing.pro.feature7': 'تنبيهات مخصصة (SMS, WhatsApp)',
    'pricing.pro.feature8': 'تقارير بالعلامة البيضاء',
    'pricing.pro.feature9': 'مدير حساب مخصص',
    'pricing.enterprise.name': 'مؤسسات',
    'pricing.enterprise.period': 'شهر',
    'pricing.enterprise.description': 'للمؤسسات الكبيرة مع احتياجات متقدمة',
    'pricing.enterprise.feature1': 'كل شيء في البرو',
    'pricing.enterprise.feature2': 'وصول API غير محدود',
    'pricing.enterprise.feature3': 'تكاملات مخصصة',
    'pricing.enterprise.feature4': 'خلاصات بيانات فورية',
    'pricing.enterprise.feature5': 'تحليلات متقدمة',
    'pricing.enterprise.feature6': 'بنية تحتية مخصصة',
    'pricing.enterprise.feature7': 'اتفاقية مستوى خدمة مخصصة',
    'pricing.enterprise.feature8': 'خيار النشر المحلي',
    'pricing.enterprise.feature9': 'خصومات كبيرة',
    'footer.about': 'عن PriceX',
    'footer.contact': 'اتصل بنا',
    'footer.privacy': 'سياسة الخصوصية',
    'footer.terms': 'شروط الخدمة',
    'footer.help': 'مركز المساعدة',
    'footer.careers': 'وظائف',
    'footer.newsletter': 'النشرة الإخبارية',
    'footer.newsletterText': 'اشترك للحصول على أحدث العروض',
    'footer.subscribe': 'اشترك',
    'footer.email': 'أدخل بريدك الإلكتروني',
    'footer.copyright': '© 2024 PriceX. جميع الحقوق محفوظة.',
    'footer.followUs': 'تابعنا',
    'footer.company': 'الشركة',
    'footer.support': 'الدعم',
    'footer.legal': 'قانوني',
    'footer.partners': 'الشركاء',
    'footer.press': 'الصحافة',
    'footer.blog': 'المدونة',
    'footer.faqs': 'الأسئلة الشائعة',
    'footer.feedback': 'ملاحظات',
    'footer.cookies': 'سياسة ملفات تعريف الارتباط',
    'footer.accessibility': 'إمكانية الوصول',
    'footer.retailers': 'للمتاجر',
    'footer.brands': 'للبراندات',
    'footer.advertise': 'إعلن معنا',
    'footer.apiAccess': 'وصول API',
    'footer.stayUpdated': 'ابق على اطلاع',
    'common.loading': 'جاري التحميل...',
    'common.error': 'خطأ',
    'common.retry': 'إعادة المحاولة',
    'common.cancel': 'إلغاء',
    'common.save': 'حفظ',
    'common.close': 'إغلاق',
    'common.seeAll': 'عرض الكل',
    'common.viewAll': 'عرض الكل',
    'common.learnMore': 'اعرف المزيد',
    'common.getStarted': 'ابدأ الآن',
    'common.continue': 'متابعة',
    'common.back': 'رجوع',
    'common.next': 'التالي',
    'common.done': 'تم',
    'common.today': 'اليوم',
    'common.yesterday': 'أمس',
    'common.thisWeek': 'هذا الأسبوع',
    'common.thisMonth': 'هذا الشهر',
    'common.all': 'الكل',
    'common.none': 'لا شيء',
    'common.or': 'أو',
    'common.and': 'و',
    'common.theme': 'السمة',
    'common.light': 'فاتح',
    'common.dark': 'داكن',
    'common.auto': 'تلقائي',
    'admin.dashboard': 'لوحة التحكم',
    'admin.users': 'المستخدمون',
    'admin.products': 'المنتجات',
    'admin.orders': 'الطلبات',
    'admin.settings': 'الإعدادات',
    'error.general': 'حدث خطأ ما',
    'error.network': 'خطأ في الشبكة',
    'error.notFound': 'غير موجود',
    'success.saved': 'تم الحفظ بنجاح',
    'success.deleted': 'تم الحذف بنجاح',
    'priceHistory.title': 'تاريخ الأسعار',
    'priceHistory.lowest': 'الأقل',
    'priceHistory.highest': 'الأعلى',
    'priceHistory.average': 'المتوسط',
    'priceHistory.current': 'الحالي',
    'priceHistory.change': 'التغيير',
    'priceHistory.date': 'التاريخ',
    'priceHistory.trend': 'الاتجاه',
  },
  es: {
    'app.name': 'PriceX',
    'app.tagline': 'Comparación Global de Precios con IA',
    'app.description': 'Encuentra los mejores precios en millones de productos de miles de vendedores.',
    'nav.home': 'Inicio',
    'nav.search': 'Buscar',
    'nav.categories': 'Categorías',
    'nav.deals': 'Ofertas',
    'nav.alerts': 'Alertas de Precio',
    'nav.account': 'Mi Cuenta',
    'nav.compare': 'Comparar',
    'nav.cashback': 'Cashback',
    'nav.login': 'Iniciar Sesión',
    'nav.register': 'Registrarse',
    'nav.logout': 'Cerrar Sesión',
    'nav.admin': 'Admin',
    'search.placeholder': 'Buscar productos, marcas o categorías...',
    'search.button': 'Buscar',
    'search.noResults': 'No se encontraron resultados',
    'region.select': 'Seleccionar Región',
    'language.select': 'Seleccionar Idioma',
    'currency.select': 'Seleccionar Moneda',
    'product.compare': 'Comparar Precios',
    'product.priceHistory': 'Historial de Precios',
    'product.alert': 'Establecer Alerta',
    'product.buyNow': 'Comprar Ahora',
    'product.viewDeal': 'Ver Oferta',
    'product.inStock': 'En Stock',
    'product.outOfStock': 'Agotado',
    'product.freeShipping': 'Envío Gratis',
    'product.official': 'Tienda Oficial',
    'alerts.title': 'Alertas de Precio',
    'alerts.create': 'Crear Alerta',
    'deals.title': 'Ofertas Calientes',
    'compare.title': 'Comparar Productos',
    'categories.title': 'Categorías',
    'auth.login': 'Iniciar Sesión',
    'auth.register': 'Registrarse',
    'auth.email': 'Correo Electrónico',
    'auth.password': 'Contraseña',
    'home.hero.title': 'Encuentra los Mejores Precios',
    'home.hero.subtitle': 'Compara millones de productos de miles de vendedores',
    'home.features.title': 'Por Qué Elegir PriceX',
    'home.features.aiSearch': 'Búsqueda con IA',
    'home.features.priceHistory': 'Historial de Precios',
    'home.features.smartAlerts': 'Alertas Inteligentes',
    'home.stats.users': 'Usuarios Activos',
    'home.stats.products': 'Productos Rastreados',
    'home.stats.retailers': 'Vendedores',
    'home.stats.countries': 'Países',
    'home.categories.title': 'Categorías Populares',
    'categories.electronics': 'Electrónicos',
    'categories.fashion': 'Moda',
    'categories.home': 'Hogar y Jardín',
    'categories.sports': 'Deportes',
    'categories.beauty': 'Belleza',
    'categories.automotive': 'Automotriz',
    'categories.toys': 'Juguetes',
    'categories.books': 'Libros',
    'categories.products': 'productos',
    'footer.about': 'Sobre PriceX',
    'footer.contact': 'Contacto',
    'footer.privacy': 'Política de Privacidad',
    'footer.terms': 'Términos de Servicio',
    'common.loading': 'Cargando...',
    'common.error': 'Error',
    'common.cancel': 'Cancelar',
    'common.save': 'Guardar',
    'footer.company': 'Empresa',
    'footer.support': 'Soporte',
    'footer.legal': 'Legal',
    'footer.partners': 'Socios',
    'footer.press': 'Prensa',
    'footer.blog': 'Blog',
    'footer.faqs': 'Preguntas Frecuentes',
    'footer.feedback': 'Comentarios',
    'footer.cookies': 'Política de Cookies',
    'footer.accessibility': 'Accesibilidad',
    'footer.retailers': 'Para Minoristas',
    'footer.brands': 'Para Marcas',
    'footer.advertise': 'Anunciar',
    'footer.apiAccess': 'Acceso API',
    'footer.stayUpdated': 'Mantente Actualizado',
    'pricing.title': 'Elige tu plan de',
    'pricing.plan': 'Plan',
    'pricing.monthly': 'Mensual',
    'pricing.yearly': 'Anual',
    'pricing.save': 'Ahorra',
    'pricing.mostPopular': 'Más Popular',
    'pricing.billedAnnually': 'mes (facturado anualmente)',
    'pricing.perMonth': 'mes',
    'pricing.getStarted': 'Comenzar',
    'pricing.subscribe': 'Suscribirse',
    'pricing.moneyBack': 'Garantía de 30 días',
    'pricing.cancel': 'Cancelar en cualquier momento',
    'pricing.usersTrust': '10M+ usuarios confían en PriceX',
    'home.pricing.title': 'Planes Premium',
    'home.pricing.subtitle': 'Desbloquea funciones avanzadas',
    'home.features.title': 'Por Qué Elegir PriceX',
  },
  fr: {
    'app.name': 'PriceX',
    'app.tagline': 'Comparaison de Prix Mondiale IA',
    'app.description': 'Trouvez les meilleurs prix sur des millions de produits auprès de milliers de vendeurs.',
    'nav.home': 'Accueil',
    'nav.search': 'Rechercher',
    'nav.categories': 'Catégories',
    'nav.deals': 'Offres',
    'nav.alerts': 'Alertes Prix',
    'nav.account': 'Mon Compte',
    'nav.compare': 'Comparer',
    'nav.cashback': 'Cashback',
    'nav.login': 'Connexion',
    'nav.register': "S'inscrire",
    'nav.logout': 'Déconnexion',
    'search.placeholder': 'Rechercher des produits, marques ou catégories...',
    'search.button': 'Rechercher',
    'search.noResults': 'Aucun résultat trouvé',
    'region.select': 'Sélectionner Région',
    'language.select': 'Sélectionner Langue',
    'currency.select': 'Sélectionner Devise',
    'product.compare': 'Comparer Prix',
    'product.priceHistory': 'Historique Prix',
    'product.alert': 'Définir Alerte',
    'product.buyNow': 'Acheter Maintenant',
    'product.inStock': 'En Stock',
    'product.outOfStock': 'Rupture de Stock',
    'product.freeShipping': 'Livraison Gratuite',
    'product.official': 'Boutique Officielle',
    'alerts.title': 'Alertes Prix',
    'alerts.create': 'Créer Alerte',
    'deals.title': 'Offres Chaudes',
    'compare.title': 'Comparer Produits',
    'categories.title': 'Catégories',
    'categories.electronics': 'Électronique',
    'categories.fashion': 'Mode',
    'categories.home': 'Maison et Jardin',
    'categories.sports': 'Sports',
    'categories.beauty': 'Beauté',
    'categories.automotive': 'Automobile',
    'categories.toys': 'Jeux',
    'categories.books': 'Livres',
    'categories.products': 'produits',
    'auth.login': 'Connexion',
    'auth.register': "S'inscrire",
    'auth.email': 'Email',
    'auth.password': 'Mot de passe',
    'home.hero.title': 'Trouvez les Meilleurs Prix',
    'home.hero.subtitle': 'Comparez des millions de produits de milliers de vendeurs',
    'home.features.title': 'Pourquoi Choisir PriceX',
    'home.features.aiSearch': 'Recherche IA',
    'home.features.priceHistory': 'Historique des Prix',
    'home.features.smartAlerts': 'Alertes Intelligentes',
    'home.stats.users': 'Utilisateurs Actifs',
    'home.stats.products': 'Produits Suivis',
    'home.stats.retailers': 'Vendeurs',
    'home.stats.countries': 'Pays',
    'home.categories.title': 'Catégories Populaires',
    'footer.about': 'À Propos',
    'footer.contact': 'Contact',
    'footer.privacy': 'Confidentialité',
    'footer.terms': 'Conditions',
    'common.loading': 'Chargement...',
    'common.error': 'Erreur',
    'common.cancel': 'Annuler',
    'common.save': 'Enregistrer',
    'footer.company': 'Entreprise',
    'footer.support': 'Support',
    'footer.legal': 'Légal',
    'footer.partners': 'Partenaires',
    'footer.press': 'Presse',
    'footer.blog': 'Blog',
    'footer.faqs': 'FAQ',
    'footer.feedback': 'Commentaires',
    'footer.cookies': 'Politique des Cookies',
    'footer.accessibility': 'Accessibilité',
    'footer.retailers': 'Pour les Détaillants',
    'footer.brands': 'Pour les Marques',
    'footer.advertise': 'Publicité',
    'footer.apiAccess': 'Accès API',
    'footer.stayUpdated': 'Restez Informé',
    'pricing.title': 'Choisissez votre plan',
    'pricing.plan': 'Plan',
    'pricing.monthly': 'Mensuel',
    'pricing.yearly': 'Annuel',
    'pricing.save': 'Économisez',
    'pricing.mostPopular': 'Plus Populaire',
    'pricing.billedAnnually': 'mois (facturé annuellement)',
    'pricing.perMonth': 'mois',
    'pricing.getStarted': 'Commencer',
    'pricing.subscribe': "S'abonner",
    'pricing.moneyBack': 'Garantie 30 jours',
    'pricing.cancel': 'Annuler à tout moment',
    'pricing.usersTrust': '10M+ utilisateurs font confiance à PriceX',
    'home.pricing.title': 'Plans Premium',
    'home.pricing.subtitle': 'Débloquez des fonctionnalités avancées',
    'home.features.title': 'Pourquoi Choisir PriceX',
  },
  it: {
    'app.name': 'PriceX',
    'app.tagline': 'Confronto Prezzi Globale AI',
    'app.description': 'Trova i migliori prezzi su milioni di prodotti da migliaia di rivenditori.',
    'nav.home': 'Home',
    'nav.search': 'Cerca',
    'nav.categories': 'Categorie',
    'nav.deals': 'Offerte',
    'nav.alerts': 'Alert Prezzi',
    'nav.account': 'Account',
    'nav.compare': 'Confronta',
    'nav.cashback': 'Cashback',
    'nav.login': 'Accedi',
    'nav.register': 'Registrati',
    'search.placeholder': 'Cerca prodotti, marchi o categorie...',
    'search.button': 'Cerca',
    'search.noResults': 'Nessun risultato trovato',
    'region.select': 'Seleziona Regione',
    'language.select': 'Seleziona Lingua',
    'currency.select': 'Seleziona Valuta',
    'product.compare': 'Confronta Prezzi',
    'product.priceHistory': 'Storico Prezzi',
    'product.alert': 'Imposta Alert',
    'product.buyNow': 'Ac Ora',
    'product.inStock': 'Disponibile',
    'product.outOfStock': 'Non Disponibile',
    'product.freeShipping': 'Spedizione Gratuita',
    'product.official': 'Negozio Ufficiale',
    'alerts.title': 'Alert Prezzi',
    'alerts.create': 'Crea Alert',
    'deals.title': 'Offerte Calde',
    'compare.title': 'Confronta Prodotti',
    'categories.title': 'Categorie',
    'categories.electronics': 'Elettronica',
    'categories.fashion': 'Moda',
    'categories.home': 'Casa e Giardino',
    'categories.sports': 'Sport',
    'categories.beauty': 'Bellezza',
    'categories.automotive': 'Automotive',
    'categories.toys': 'Giocattoli',
    'categories.books': 'Libri',
    'categories.products': 'prodotti',
    'auth.login': 'Accedi',
    'auth.register': 'Registrati',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'home.hero.title': 'Trova i Migliori Prezzi',
    'home.hero.subtitle': 'Confronta milioni di prodotti da migliaia di rivenditori',
    'home.features.title': 'Perché Scegliere PriceX',
    'home.features.aiSearch': 'Ricerca AI',
    'home.features.priceHistory': 'Storico Prezzi',
    'home.features.smartAlerts': 'Alert Intelligenti',
    'home.stats.users': 'Utenti Attivi',
    'home.stats.products': 'Prodotti Tracciati',
    'home.stats.retailers': 'Rivenditori',
    'home.stats.countries': 'Paesi',
    'home.categories.title': 'Categorie Popolari',
    'footer.about': 'Chi Siamo',
    'footer.contact': 'Contatti',
    'footer.privacy': 'Privacy',
    'footer.terms': 'Termini',
    'common.loading': 'Caricamento...',
    'common.error': 'Errore',
    'common.cancel': 'Annulla',
    'common.save': 'Salva',
    'footer.company': 'Azienda',
    'footer.support': 'Supporto',
    'footer.legal': 'Legale',
    'footer.partners': 'Partner',
    'footer.press': 'Stampa',
    'footer.blog': 'Blog',
    'footer.faqs': 'FAQ',
    'footer.feedback': 'Feedback',
    'footer.cookies': 'Cookie Policy',
    'footer.accessibility': 'Accessibilità',
    'footer.retailers': 'Per Rivenditori',
    'footer.brands': 'Per Marchi',
    'footer.advertise': 'Pubblicizza',
    'footer.apiAccess': 'Accesso API',
    'footer.stayUpdated': 'Rimani Aggiornato',
    'pricing.title': 'Scegli il tuo',
    'pricing.plan': 'Piano',
    'pricing.monthly': 'Mensile',
    'pricing.yearly': 'Annuale',
    'pricing.save': 'Risparmia',
    'pricing.mostPopular': 'Più Popolare',
    'pricing.billedAnnually': 'mese (fatturato annualmente)',
    'pricing.perMonth': 'mese',
    'pricing.getStarted': 'Inizia',
    'pricing.subscribe': 'Iscriviti',
    'pricing.moneyBack': 'Garanzia 30 giorni',
    'pricing.cancel': 'Annulla quando vuoi',
    'pricing.usersTrust': '10M+ utenti si fidano di PriceX',
    'home.pricing.title': 'Piani Premium',
    'home.pricing.subtitle': 'Sblocca funzionalità avanzate',
    'home.features.title': 'Perché Scegliere PriceX',
  },
  zh: {
    'app.name': 'PriceX',
    'app.tagline': '全球AI驱动价格比较平台',
    'app.description': '在全球数千家零售商中寻找数百万产品的最优价格。',
    'nav.home': '首页',
    'nav.search': '搜索',
    'nav.categories': '分类',
    'nav.deals': '热门优惠',
    'nav.alerts': '价格提醒',
    'nav.account': '我的账户',
    'nav.compare': '比较',
    'nav.cashback': '返现',
    'nav.login': '登录',
    'nav.register': '注册',
    'nav.logout': '退出',
    'search.placeholder': '搜索产品、品牌或分类...',
    'search.button': '搜索',
    'search.noResults': '未找到结果',
    'region.select': '选择地区',
    'language.select': '选择语言',
    'currency.select': '选择货币',
    'product.compare': '比较价格',
    'product.priceHistory': '价格历史',
    'product.alert': '设置提醒',
    'product.buyNow': '立即购买',
    'product.viewDeal': '查看优惠',
    'product.inStock': '有货',
    'product.outOfStock': '缺货',
    'product.freeShipping': '免费送货',
    'product.official': '官方商店',
    'product.from': '来自',
    'product.retailer': '零售商',
    'alerts.title': '价格提醒',
    'alerts.subtitle': '价格下降时获得通知',
    'alerts.create': '创建提醒',
    'alerts.noAlerts': '暂无价格提醒',
    'deals.title': '热门优惠',
    'deals.subtitle': '今日最优价格',
    'compare.title': '产品比较',
    'compare.noProducts': '没有可比较的产品',
    'categories.title': '分类',
    'categories.subtitle': '按分类浏览',
    'cashback.title': '返现',
    'auth.login': '登录',
    'auth.register': '注册',
    'auth.email': '邮箱',
    'auth.password': '密码',
    'home.hero.title': '寻找最优价格',
    'home.hero.subtitle': '在全球数千家零售商中比较数百万产品',
    'home.features.title': '为什么选择PriceX',
    'home.features.aiSearch': 'AI智能搜索',
    'home.features.aiSearchDesc': '智能产品匹配，涵盖全球数千家零售商的数百万商品。',
    'home.features.priceHistory': '价格历史',
    'home.features.priceHistoryDesc': '追踪价格趋势，确定最佳购买时机。',
    'home.features.smartAlerts': '智能提醒',
    'home.features.smartAlertsDesc': '价格降至目标水平时立即通知您。',
    'home.features.trustedReviews': '可信评价',
    'home.features.trustedReviewsDesc': '真实用户评价和评分，帮助您做出明智决定。',
    'home.features.realTime': '实时更新',
    'home.features.realTimeDesc': '每几分钟更新一次实时价格追踪。',
    'home.features.global': '全球覆盖',
    'home.features.globalDesc': '即时比较8个地区18种货币的价格。',
    'home.stats.users': '活跃用户',
    'home.stats.products': '追踪产品',
    'home.stats.retailers': '零售商',
    'home.stats.countries': '国家',
    'home.categories.title': '热门分类',
    'home.categories.viewAll': '查看所有分类',
    'home.pricing.title': '高级计划',
    'home.pricing.subtitle': '解锁高级功能',
    'footer.about': '关于PriceX',
    'footer.contact': '联系我们',
    'footer.privacy': '隐私政策',
    'footer.terms': '服务条款',
    'common.loading': '加载中...',
    'common.error': '错误',
    'common.retry': '重试',
    'common.cancel': '取消',
    'common.save': '保存',
    'common.close': '关闭',
    'common.seeAll': '查看全部',
    'footer.company': '公司',
    'footer.support': '支持',
    'footer.legal': '法律',
    'footer.partners': '合作伙伴',
    'footer.press': '媒体',
    'footer.blog': '博客',
    'footer.faqs': '常见问题',
    'footer.feedback': '反馈',
    'footer.cookies': 'Cookie政策',
    'footer.accessibility': '无障碍',
    'footer.retailers': '零售商',
    'footer.brands': '品牌',
    'footer.advertise': '广告',
    'footer.apiAccess': 'API访问',
    'footer.stayUpdated': '保持更新',
    'pricing.title': '选择您的计划',
    'pricing.plan': '计划',
    'pricing.monthly': '每月',
    'pricing.yearly': '每年',
    'pricing.save': '节省',
    'pricing.mostPopular': '最受欢迎',
    'pricing.billedAnnually': '月（按年付费）',
    'pricing.perMonth': '月',
    'pricing.getStarted': '开始',
    'pricing.subscribe': '订阅',
    'pricing.moneyBack': '30天退款保证',
    'pricing.cancel': '随时取消',
    'pricing.usersTrust': '1000万+用户信任PriceX',
    'home.pricing.title': '高级计划',
    'home.pricing.subtitle': '解锁高级功能',
    'home.features.title': '为什么选择PriceX',
  },
  tr: {
    'app.name': 'PriceX',
    'app.tagline': 'Küresel AI Fiyat Karşılaştırma',
    'app.description': 'Binlerce perakendeciden milyonlarca üründe en iyi fiyatları bulun.',
    'nav.home': 'Ana Sayfa',
    'nav.search': 'Ara',
    'nav.categories': 'Kategoriler',
    'nav.deals': 'Fırsatlar',
    'nav.alerts': 'Fiyat Uyarıları',
    'nav.account': 'Hesabım',
    'nav.compare': 'Karşılaştır',
    'nav.cashback': 'Nakit İade',
    'nav.login': 'Giriş Yap',
    'nav.register': 'Kayıt Ol',
    'search.placeholder': 'Ürün, marka veya kategori ara...',
    'search.button': 'Ara',
    'search.noResults': 'Sonuç bulunamadı',
    'region.select': 'Bölge Seç',
    'language.select': 'Dil Seç',
    'currency.select': 'Para Birimi Seç',
    'product.compare': 'Fiyat Karşılaştır',
    'product.priceHistory': 'Fiyat Geçmişi',
    'product.alert': 'Uyarı Ayarla',
    'product.buyNow': 'Şimdi Al',
    'product.inStock': 'Stokta Var',
    'product.outOfStock': 'Stokta Yok',
    'product.freeShipping': 'Ücretsiz Kargo',
    'product.official': 'Resmi Mağaza',
    'alerts.title': 'Fiyat Uyarıları',
    'alerts.create': 'Uyarı Oluştur',
    'deals.title': 'Fırsatlar',
    'compare.title': 'Ürünleri Karşılaştır',
    'categories.title': 'Kategoriler',
    'categories.electronics': 'Elektronik',
    'categories.fashion': 'Moda',
    'categories.home': 'Ev ve Bahçe',
    'categories.sports': 'Spor',
    'categories.beauty': 'Güzellik',
    'categories.automotive': 'Otomotiv',
    'categories.toys': 'Oyuncak',
    'categories.books': 'Kitaplar',
    'categories.products': 'ürünler',
    'auth.login': 'Giriş Yap',
    'auth.register': 'Kayıt Ol',
    'auth.email': 'E-posta',
    'auth.password': 'Şifre',
    'home.hero.title': 'En İyi Fiyatları Bulun',
    'home.hero.subtitle': 'Binlerce perakendeciden milyonlarca ürünü karşılaştırın',
    'home.features.title': 'Neden PriceX',
    'home.features.aiSearch': 'AI Destekli Arama',
    'home.features.priceHistory': 'Fiyat Geçmişi',
    'home.features.smartAlerts': 'Akıllı Uyarılar',
    'home.stats.users': 'Aktif Kullanıcılar',
    'home.stats.products': 'Takip Edilen Ürünler',
    'home.stats.retailers': 'Perakendeciler',
    'home.stats.countries': 'Ülkeler',
    'home.categories.title': 'Popüler Kategoriler',
    'footer.about': 'Hakkımızda',
    'footer.contact': 'İletişim',
    'footer.privacy': 'Gizlilik',
    'footer.terms': 'Kullanım Şartları',
    'common.loading': 'Yükleniyor...',
    'common.error': 'Hata',
    'common.cancel': 'İptal',
    'common.save': 'Kaydet',
    'footer.company': 'Şirket',
    'footer.support': 'Destek',
    'footer.legal': 'Yasal',
    'footer.partners': 'Ortaklar',
    'footer.press': 'Basın',
    'footer.blog': 'Blog',
    'footer.faqs': 'Sıkça Sorulan Sorular',
    'footer.feedback': 'Geribildirim',
    'footer.cookies': 'Çerez Politikası',
    'footer.accessibility': 'Erişilebilirlik',
    'footer.retailers': 'Perakendeciler İçin',
    'footer.brands': 'Markalar İçin',
    'footer.advertise': 'Reklam Ver',
    'footer.apiAccess': 'API Erişimi',
    'footer.stayUpdated': 'Güncel Kal',
    'pricing.title': 'Seçin',
    'pricing.plan': 'Plan',
    'pricing.monthly': 'Aylık',
    'pricing.yearly': 'Yıllık',
    'pricing.save': 'Tasarruf et',
    'pricing.mostPopular': 'En Popüler',
    'pricing.billedAnnually': 'ay (yıllık faturalandırma)',
    'pricing.perMonth': 'ay',
    'pricing.getStarted': 'Başla',
    'pricing.subscribe': 'Abone Ol',
    'pricing.moneyBack': '30 gün para iade garantisi',
    'pricing.cancel': 'İstediğiniz zaman iptal',
    'pricing.usersTrust': '10M+ kullanıcı PriceX\'e güveniyor',
    'home.pricing.title': 'Premium Planlar',
    'home.pricing.subtitle': 'Gelişmiş özelliklerin kilidini aç',
    'home.features.title': 'Neden PriceX',
  },
  ru: {
    'app.name': 'PriceX',
    'app.tagline': 'Глобальная платформа сравнения цен с ИИ',
    'app.description': 'Найдите лучшие цены на миллионы товаров у тысяч продавцов.',
    'nav.home': 'Главная',
    'nav.search': 'Поиск',
    'nav.categories': 'Категории',
    'nav.deals': 'Горящие предложения',
    'nav.alerts': 'Ценовые оповещения',
    'nav.account': 'Мой аккаунт',
    'nav.compare': 'Сравнить',
    'nav.cashback': 'Кэшбэк',
    'nav.login': 'Войти',
    'nav.register': 'Регистрация',
    'search.placeholder': 'Поиск товаров, брендов или категорий...',
    'search.button': 'Поиск',
    'search.noResults': 'Результатов не найдено',
    'region.select': 'Выбрать регион',
    'language.select': 'Выбрать язык',
    'currency.select': 'Выбрать валюту',
    'product.compare': 'Сравнить цены',
    'product.priceHistory': 'История цен',
    'product.alert': 'Установить оповещение',
    'product.buyNow': 'Купить сейчас',
    'product.inStock': 'В наличии',
    'product.outOfStock': 'Нет в наличии',
    'product.freeShipping': 'Бесплатная доставка',
    'product.official': 'Официальный магазин',
    'alerts.title': 'Ценовые оповещения',
    'alerts.create': 'Создать оповещение',
    'deals.title': 'Горящие предложения',
    'compare.title': 'Сравнить товары',
    'categories.title': 'Категории',
    'categories.electronics': 'Электроника',
    'categories.fashion': 'Мода',
    'categories.home': 'Дом и сад',
    'categories.sports': 'Спорт',
    'categories.beauty': 'Красота',
    'categories.automotive': 'Авто',
    'categories.toys': 'Игрушки',
    'categories.books': 'Книги',
    'categories.products': 'товаров',
    'auth.login': 'Войти',
    'auth.register': 'Регистрация',
    'auth.email': 'Email',
    'auth.password': 'Пароль',
    'home.hero.title': 'Найдите лучшие цены',
    'home.hero.subtitle': 'Сравните миллионы товаров у тысяч продавцов',
    'home.features.title': 'Почему PriceX',
    'home.features.aiSearch': 'Поиск с ИИ',
    'home.features.priceHistory': 'История цен',
    'home.features.smartAlerts': 'Умные оповещения',
    'home.stats.users': 'Активные пользователи',
    'home.stats.products': 'Отслеживаемые товары',
    'home.stats.retailers': 'Продавцы',
    'home.stats.countries': 'Страны',
    'home.categories.title': 'Популярные категории',
    'footer.about': 'О PriceX',
    'footer.contact': 'Контакты',
    'footer.privacy': 'Политика конфиденциальности',
    'footer.terms': 'Условия использования',
    'common.loading': 'Загрузка...',
    'common.error': 'Ошибка',
    'common.cancel': 'Отмена',
    'common.save': 'Сохранить',
    'footer.company': 'Компания',
    'footer.support': 'Поддержка',
    'footer.legal': 'Право',
    'footer.partners': 'Партнеры',
    'footer.press': 'Пресса',
    'footer.blog': 'Блог',
    'footer.faqs': 'Частые вопросы',
    'footer.feedback': 'Отзывы',
    'footer.cookies': 'Политика Cookies',
    'footer.accessibility': 'Доступность',
    'footer.retailers': 'Для ритейлеров',
    'footer.brands': 'Для брендов',
    'footer.advertise': 'Реклама',
    'footer.apiAccess': 'Доступ к API',
    'footer.stayUpdated': 'Оставайтесь в курсе',
    'pricing.title': 'Выберите',
    'pricing.plan': 'План',
    'pricing.monthly': 'Месяц',
    'pricing.yearly': 'Год',
    'pricing.save': 'Экономьте',
    'pricing.mostPopular': 'Популярное',
    'pricing.billedAnnually': 'мес (оплата ежегодно)',
    'pricing.perMonth': 'мес',
    'pricing.getStarted': 'Начать',
    'pricing.subscribe': 'Подписаться',
    'pricing.moneyBack': 'Гарантия возврата 30 дней',
    'pricing.cancel': 'Отмена в любое время',
    'pricing.usersTrust': '10M+ пользователей доверяют PriceX',
    'home.pricing.title': 'Премиум планы',
    'home.pricing.subtitle': 'Откройте расширенные функции',
    'home.features.title': 'Почему PriceX',
  },
  pt: {
    'app.name': 'PriceX',
    'app.tagline': 'Comparação Global de Preços com IA',
    'app.description': 'Encontre os melhores preços em milhões de produtos de milhares de lojas.',
    'nav.home': 'Início',
    'nav.search': 'Pesquisar',
    'nav.categories': 'Categorias',
    'nav.deals': 'Ofertas',
    'nav.alerts': 'Alertas de Preço',
    'nav.account': 'Minha Conta',
    'nav.compare': 'Comparar',
    'nav.cashback': 'Cashback',
    'nav.login': 'Entrar',
    'nav.register': 'Cadastrar',
    'search.placeholder': 'Pesquisar produtos, marcas ou categorias...',
    'search.button': 'Pesquisar',
    'search.noResults': 'Nenhum resultado encontrado',
    'region.select': 'Selecionar Região',
    'language.select': 'Selecionar Idioma',
    'currency.select': 'Selecionar Moeda',
    'product.compare': 'Comparar Preços',
    'product.priceHistory': 'Histórico de Preços',
    'product.alert': 'Definir Alerta',
    'product.buyNow': 'Comprar Agora',
    'product.inStock': 'Em Estoque',
    'product.outOfStock': 'Fora de Estoque',
    'product.freeShipping': 'Frete Grátis',
    'product.official': 'Loja Oficial',
    'alerts.title': 'Alertas de Preço',
    'alerts.create': 'Criar Alerta',
    'deals.title': 'Ofertas',
    'compare.title': 'Comparar Produtos',
    'categories.title': 'Categorias',
    'categories.electronics': 'Eletrônicos',
    'categories.fashion': 'Moda',
    'categories.home': 'Casa e Jardim',
    'categories.sports': 'Esportes',
    'categories.beauty': 'Beleza',
    'categories.automotive': 'Automotivo',
    'categories.toys': 'Brinquedos',
    'categories.books': 'Livros',
    'categories.products': 'produtos',
    'auth.login': 'Entrar',
    'auth.register': 'Cadastrar',
    'auth.email': 'Email',
    'auth.password': 'Senha',
    'home.hero.title': 'Encontre os Melhores Preços',
    'home.hero.subtitle': 'Compare milhões de produtos de milhares de lojas',
    'home.features.title': 'Por Que Escolher PriceX',
    'home.features.aiSearch': 'Busca com IA',
    'home.features.priceHistory': 'Histórico de Preços',
    'home.features.smartAlerts': 'Alertas Inteligentes',
    'home.stats.users': 'Usuários Ativos',
    'home.stats.products': 'Produtos Rastreados',
    'home.stats.retailers': 'Lojas',
    'home.stats.countries': 'Países',
    'home.categories.title': 'Categorias Populares',
    'footer.about': 'Sobre PriceX',
    'footer.contact': 'Contato',
    'footer.privacy': 'Política de Privacidade',
    'footer.terms': 'Termos de Serviço',
    'common.loading': 'Carregando...',
    'common.error': 'Erro',
    'common.cancel': 'Cancelar',
    'common.save': 'Salvar',
    'footer.company': 'Empresa',
    'footer.support': 'Suporte',
    'footer.legal': 'Legal',
    'footer.partners': 'Parceiros',
    'footer.press': 'Imprensa',
    'footer.blog': 'Blog',
    'footer.faqs': 'Perguntas Frequentes',
    'footer.feedback': 'Feedback',
    'footer.cookies': 'Política de Cookies',
    'footer.accessibility': 'Acessibilidade',
    'footer.retailers': 'Para Varejistas',
    'footer.brands': 'Para Marcas',
    'footer.advertise': 'Anunciar',
    'footer.apiAccess': 'Acesso API',
    'footer.stayUpdated': 'Fique Atualizado',
    'pricing.title': 'Escolha seu',
    'pricing.plan': 'Plano',
    'pricing.monthly': 'Mensal',
    'pricing.yearly': 'Anual',
    'pricing.save': 'Economize',
    'pricing.mostPopular': 'Mais Popular',
    'pricing.billedAnnually': 'mês (facturado anualmente)',
    'pricing.perMonth': 'mês',
    'pricing.getStarted': 'Começar',
    'pricing.subscribe': 'Assinar',
    'pricing.moneyBack': 'Garantia de 30 dias',
    'pricing.cancel': 'Cancele a qualquer momento',
    'pricing.usersTrust': '10M+ usuários confiam na PriceX',
    'home.pricing.title': 'Planos Premium',
    'home.pricing.subtitle': 'Desbloqueie recursos avançados',
    'home.features.title': 'Por Que Escolher PriceX',
  },
  ur: {
    'app.name': 'PriceX',
    'app.tagline': 'عالمی AI قیمت موازنہ پلیٹ فارم',
    'app.description': 'ہزاروں تاجروں سے لاکھوں مصنوعات پر بہترین قیمتیں تلاش کریں۔',
    'nav.home': 'ہوم',
    'nav.search': 'تلاش',
    'nav.categories': 'زمرہ جات',
    'nav.deals': 'ہاٹ ڈیلز',
    'nav.alerts': 'قیمت الرٹس',
    'nav.account': 'میرا اکاؤنٹ',
    'nav.compare': 'موازنہ',
    'nav.cashback': 'کیش بیک',
    'nav.login': 'لاگ ان',
    'nav.register': 'سائن اپ',
    'search.placeholder': 'مصنوعات، برانڈز یا زمرہ جات تلاش کریں...',
    'search.button': 'تلاش',
    'search.noResults': 'کوئی نتیجہ نہیں ملی',
    'region.select': 'علاقہ انتخاب کریں',
    'language.select': 'زبان انتخاب کریں',
    'currency.select': 'کرنسی انتخاب کریں',
    'product.compare': 'قیمتوں کا موازنہ',
    'product.priceHistory': 'قیمت کی تاریخ',
    'product.alert': 'الرٹ سیٹ کریں',
    'product.buyNow': 'اب خریديں',
    'product.inStock': 'اسٹاک میں',
    'product.outOfStock': 'اسٹاک ختم',
    'product.freeShipping': 'مفت shipping',
    'product.official': 'سرکاری دکان',
    'alerts.title': 'قیمت الرٹس',
    'alerts.create': 'الرٹ بنائیں',
    'deals.title': 'ہاٹ ڈیلز',
    'compare.title': 'مصنوعات کا موازنہ',
    'categories.title': 'زمرہ جات',
    'categories.electronics': 'الیکٹرانکس',
    'categories.fashion': 'فیشن',
    'categories.home': 'گھر اور باغ',
    'categories.sports': 'کھیل',
    'categories.beauty': 'خوبصورتی',
    'categories.automotive': 'آٹوموٹو',
    'categories.toys': 'کھلونے',
    'categories.books': 'کتابیں',
    'categories.products': 'مصنوعات',
    'auth.login': 'لاگ ان',
    'auth.register': 'سائن اپ',
    'auth.email': 'ای میل',
    'auth.password': 'پاس ورڈ',
    'home.hero.title': 'بہترین قیمتیں تلاش کریں',
    'home.hero.subtitle': 'ہزاروں تاجروں سے لاکھوں مصنوعات کا موازنہ کریں',
    'home.features.title': 'PriceX کیوں چنیں',
    'home.features.aiSearch': 'AI تلاش',
    'home.features.priceHistory': 'قیمت کی تاریخ',
    'home.features.smartAlerts': 'سمارٹ الرٹس',
    'home.stats.users': 'فعال صارفین',
    'home.stats.products': 'ٹریکڈ مصنوعات',
    'home.stats.retailers': 'تاجر',
    'home.stats.countries': 'ممالک',
    'home.categories.title': 'مشہور زمرہ جات',
    'footer.about': 'PriceX کے بارے میں',
    'footer.contact': 'رابطہ کریں',
    'footer.privacy': 'رازداری کی پالیسی',
    'footer.terms': 'سروس کی شرائط',
    'common.loading': 'لوڈ ہو رہا ہے...',
    'common.error': 'خرابی',
    'common.cancel': 'منسوخ کریں',
    'common.save': 'محفوظ کریں',
    'footer.company': 'کمپنی',
    'footer.support': 'سپورٹ',
    'footer.legal': 'قانونی',
    'footer.partners': 'شراکت دار',
    'footer.press': 'پریس',
    'footer.blog': 'بلاگ',
    'footer.faqs': 'عمومی سوالات',
    'footer.feedback': 'رائے',
    'footer.cookies': 'کوکی پالیسی',
    'footer.accessibility': 'رسائی',
    'footer.retailers': 'ریٹیلرز کے لیے',
    'footer.brands': 'برانڈز کے لیے',
    'footer.advertise': 'اشتہار',
    'footer.apiAccess': 'API رسائی',
    'footer.stayUpdated': 'اپ ڈیٹڈ رہیں',
    'pricing.title': 'اپنا انتخاب کریں',
    'pricing.plan': 'پلان',
    'pricing.monthly': 'ماہانہ',
    'pricing.yearly': 'سالانہ',
    'pricing.save': 'بچت کریں',
    'pricing.mostPopular': 'سب سے مقبول',
    'pricing.billedAnnually': 'ماہ (سالانہ بل)',
    'pricing.perMonth': 'ماہ',
    'pricing.getStarted': 'شروع کریں',
    'pricing.subscribe': 'سبسکرائب',
    'pricing.moneyBack': '30 دن کی پیسے واپسی کی گارنٹی',
    'pricing.cancel': 'کسی بھی وقت منسوخ کریں',
    'pricing.usersTrust': '10M+ صارفین PriceX پر بھروسہ کرتے ہیں',
    'home.pricing.title': 'پریمیم پلانز',
    'home.pricing.subtitle': 'جدید فیچرز کا احاطہ کریں',
    'home.features.title': 'PriceX کیوں چنیں',
  },
  hi: {
    'app.name': 'PriceX',
    'app.tagline': 'वैश्विक AI मूल्य तुलना प्लेटफॉर्म',
    'app.description': 'हजारों व्यापारियों से लाखों उत्पादों पर सर्वोत्तम मूल्य खोजें।',
    'nav.home': 'होम',
    'nav.search': 'खोज',
    'nav.categories': 'श्रेणियाँ',
    'nav.deals': 'हॉट डील्स',
    'nav.alerts': 'मूल्य अलर्ट',
    'nav.account': 'मेरा खाता',
    'nav.compare': 'तुलना',
    'nav.cashback': 'कैशबैक',
    'nav.login': 'लॉगिन',
    'nav.register': 'साइन अप',
    'search.placeholder': 'उत्पाद, ब्रांड या श्रेणियाँ खोजें...',
    'search.button': 'खोज',
    'search.noResults': 'कोई परिणाम नहीं मिला',
    'region.select': 'क्षेत्र चुनें',
    'language.select': 'भाषा चुनें',
    'currency.select': 'मुद्रा चुनें',
    'product.compare': 'मूल्य तुलना',
    'product.priceHistory': 'मूल्य इतिहास',
    'product.alert': 'अलर्ट सेट करें',
    'product.buyNow': 'अभी खरीदें',
    'product.inStock': 'स्टॉक में',
    'product.outOfStock': 'स्टॉक में नहीं',
    'product.freeShipping': 'मुफ्त शिपिंग',
    'product.official': 'आधिकारिक स्टोर',
    'alerts.title': 'मूल्य अलर्ट',
    'alerts.create': 'अलर्ट बनाएं',
    'deals.title': 'हॉट डील्स',
    'compare.title': 'उत्पाद तुलना',
    'categories.title': 'श्रेणियाँ',
    'categories.electronics': 'इलेक्ट्रॉनिक्स',
    'categories.fashion': 'फैशन',
    'categories.home': 'घर और बगीचा',
    'categories.sports': 'खेल',
    'categories.beauty': 'सुंदरता',
    'categories.automotive': 'ऑटोमोटिव',
    'categories.toys': 'खिलौने',
    'categories.books': 'किताबें',
    'categories.products': 'उत्पाद',
    'auth.login': 'लॉगिन',
    'auth.register': 'साइन अप',
    'auth.email': 'ईमेल',
    'auth.password': 'पासवर्ड',
    'home.hero.title': 'सर्वोत्तम मूल्य खोजें',
    'home.hero.subtitle': 'हजारों व्यापारियों से लाखों उत्पादों की तुलना करें',
    'home.features.title': 'PriceX क्यों चुनें',
    'home.features.aiSearch': 'AI खोज',
    'home.features.priceHistory': 'मूल्य इतिहास',
    'home.features.smartAlerts': 'स्मार्ट अलर्ट',
    'home.stats.users': 'सक्रिय उपयोगकर्ता',
    'home.stats.products': 'ट्रैक उत्पाद',
    'home.stats.retailers': 'व्यापारी',
    'home.stats.countries': 'देश',
    'home.categories.title': 'लोकप्रिय श्रेणियाँ',
    'footer.about': 'PriceX के बारे में',
    'footer.contact': 'संपर्क करें',
    'footer.privacy': 'गोपनीयता नीति',
    'footer.terms': 'सेवा की शर्तें',
    'common.loading': 'लोड हो रहा है...',
    'common.error': 'त्रुटि',
    'common.cancel': 'रद्द करें',
    'common.save': 'सहेजें',
    'footer.company': 'कंपनी',
    'footer.support': 'सहायता',
    'footer.legal': 'कानूनी',
    'footer.partners': 'भागीदार',
    'footer.press': 'प्रेस',
    'footer.blog': 'ब्लॉग',
    'footer.faqs': 'सामान्य प्रश्न',
    'footer.feedback': 'प्रतिक्रिया',
    'footer.cookies': 'कुकी नीति',
    'footer.accessibility': 'सुलभता',
    'footer.retailers': 'रिटेलर्स के लिए',
    'footer.brands': 'ब्रांड्स के लिए',
    'footer.advertise': 'विज्ञापन',
    'footer.apiAccess': 'API एक्सेस',
    'footer.stayUpdated': 'अपडेटेड रहें',
    'pricing.title': 'अपना चुनें',
    'pricing.plan': 'प्लान',
    'pricing.monthly': 'मासिक',
    'pricing.yearly': 'वार्षिक',
    'pricing.save': 'बचत करें',
    'pricing.mostPopular': 'सबसे लोकप्रिय',
    'pricing.billedAnnually': 'महीना (वार्षिक बिल)',
    'pricing.perMonth': 'महीना',
    'pricing.getStarted': 'शुरू करें',
    'pricing.subscribe': 'सब्सक्राइब करें',
    'pricing.moneyBack': '30 दिन की मनी बैक गारंटी',
    'pricing.cancel': 'कभी भी रद्द करें',
    'pricing.usersTrust': '10M+ उपयोगकर्ता PriceX पर भरोसा करते हैं',
    'home.pricing.title': 'प्रीमियम प्लान',
    'home.pricing.subtitle': 'उन्नत सुविधाओं को अनलॉक करें',
    'home.features.title': 'PriceX क्यों चुनें',
  },
  ko: {
    'app.name': 'PriceX',
    'app.tagline': '글로벌 AI 기반 가격 비교 플랫폼',
    'app.description': '수천 명의 판매자로부터 수백만 개의 제품에서 최적의 가격을 찾으세요.',
    'nav.home': '홈',
    'nav.search': '검색',
    'nav.categories': '카테고리',
    'nav.deals': '핫딜',
    'nav.alerts': '가격 알림',
    'nav.account': '내 계정',
    'nav.compare': '비교',
    'nav.cashback': '캐시백',
    'nav.login': '로그인',
    'nav.register': '회원가입',
    'nav.logout': '로그아웃',
    'search.placeholder': '제품, 브랜드 또는 카테고리 검색...',
    'search.button': '검색',
    'search.noResults': '결과 없음',
    'region.select': '지역 선택',
    'language.select': '언어 선택',
    'currency.select': '통화 선택',
    'product.compare': '가격 비교',
    'product.priceHistory': '가격 기록',
    'product.alert': '알림 설정',
    'product.buyNow': '지금 구매',
    'product.viewDeal': '보기',
    'product.inStock': '재고 있음',
    'product.outOfStock': '품절',
    'product.freeShipping': '무료 배송',
    'product.official': '공식 스토어',
    'product.from': '부터',
    'product.retailer': '판매자',
    'alerts.title': '가격 알림',
    'alerts.subtitle': '가격 하락 시 알림 받기',
    'alerts.create': '알림 만들기',
    'alerts.noAlerts': '가격 알림 없음',
    'deals.title': '핫딜',
    'deals.subtitle': '오늘의 최적가',
    'compare.title': '제품 비교',
    'compare.noProducts': '비교할 제품 없음',
    'categories.title': '카테고리',
    'categories.subtitle': '카테고리로 찾아보기',
    'cashback.title': '캐시백',
    'auth.login': '로그인',
    'auth.register': '회원가입',
    'auth.email': '이메일',
    'auth.password': '비밀번호',
    'home.hero.title': '최적의 가격을 찾으세요',
    'home.hero.subtitle': '수천 명의 판매자로부터 수백만 개의 제품을 비교하세요',
    'home.features.title': 'PriceX가 특별한 이유',
    'home.features.aiSearch': 'AI 검색',
    'home.features.aiSearchDesc': '전 세계 수천 개 상점에서 수백만 개의 제품을 스마트하게 매칭합니다.',
    'home.features.priceHistory': '가격 기록',
    'home.features.priceHistoryDesc': '가격 추적을 통해 최적의 구매 시점을 파악하세요.',
    'home.features.smartAlerts': '스마트 알림',
    'home.features.smartAlertsDesc': '목표 가격 이하로 하락하면 즉시 알림을 받습니다.',
    'home.features.trustedReviews': '신뢰할 수 있는 리뷰',
    'home.features.trustedReviewsDesc': '검증된 사용자 리뷰와 평점으로 현명한 결정을 내리세요.',
    'home.features.realTime': '실시간 업데이트',
    'home.features.realTimeDesc': '몇 분마다 업데이트되는 실시간 가격 추적.',
    'home.features.global': '글로벌 커버리지',
    'home.features.globalDesc': '8개 지역, 18개 통화로 즉시 가격 비교.',
    'home.stats.users': '활성 사용자',
    'home.stats.products': '추적 중인 제품',
    'home.stats.retailers': '판매자',
    'home.stats.countries': '국가',
    'home.categories.title': '인기 카테고리',
    'home.categories.viewAll': '전체 카테고리 보기',
    'home.pricing.title': '프리미엄 플랜',
    'home.pricing.subtitle': '고급 기능 해제',
    'footer.about': 'PriceX 소개',
    'footer.contact': '문의하기',
    'footer.privacy': '개인정보 처리방침',
    'footer.terms': '서비스 이용약관',
    'common.loading': '로딩 중...',
    'common.error': '오류',
    'common.retry': '다시 시도',
    'common.cancel': '취소',
    'common.save': '저장',
    'common.close': '닫기',
    'common.seeAll': '전체 보기',
    'footer.company': '회사',
    'footer.support': '지원',
    'footer.legal': '법적',
    'footer.partners': '파트너',
    'footer.press': '보도자료',
    'footer.blog': '블로그',
    'footer.faqs': '자주 묻는 질문',
    'footer.feedback': '피드백',
    'footer.cookies': '쿠키 정책',
    'footer.accessibility': '접근성',
    'footer.retailers': '소매상을 위한',
    'footer.brands': '브랜드를 위한',
    'footer.advertise': '광고',
    'footer.apiAccess': 'API 접근',
    'footer.stayUpdated': '최신 정보 유지',
    'pricing.title': '선택하세요',
    'pricing.plan': '플랜',
    'pricing.monthly': '월간',
    'pricing.yearly': '연간',
    'pricing.save': '절약',
    'pricing.mostPopular': '인기',
    'pricing.billedAnnually': '개월 (연간 결제)',
    'pricing.perMonth': '개월',
    'pricing.getStarted': '시작하기',
    'pricing.subscribe': '구독하기',
    'pricing.moneyBack': '30일 환불 보장',
    'pricing.cancel': '언제든 취소 가능',
    'pricing.usersTrust': '1천만 이상이 PriceX를 신뢰합니다',
    'home.pricing.title': '프리미엄 플랜',
    'home.pricing.subtitle': '고급 기능 해제',
    'home.features.title': 'PriceX가 특별한 이유',
  },
};

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [currentLanguage, setCurrentLanguage] = useState<Language>(DEFAULT_LANGUAGE);
  const [isLoading, setIsLoading] = useState(true);

  const currentLanguageConfig = LANGUAGES.find(l => l.code === currentLanguage) || LANGUAGES[0];
  const isRTL = currentLanguageConfig.direction === 'rtl';
  const direction = currentLanguageConfig.direction;

  // Load language preference from localStorage
  useEffect(() => {
    const loadLanguage = () => {
      try {
        const stored = localStorage.getItem(STORAGE_KEY);
        if (stored) {
          const lang = stored as Language;
          if (LANGUAGES.some(l => l.code === lang)) {
            setCurrentLanguage(lang);
          }
        } else {
          // Try to detect browser language
          const browserLang = navigator.language.split('-')[0] as Language;
          if (LANGUAGES.some(l => l.code === browserLang)) {
            setCurrentLanguage(browserLang);
          }
        }
      } catch (error) {
        console.error('Error loading language preference:', error);
      } finally {
        setIsLoading(false);
      }
    };

    loadLanguage();
  }, []);

  // Update document direction when language changes
  useEffect(() => {
    if (typeof document !== 'undefined') {
      document.documentElement.dir = direction;
      document.documentElement.lang = currentLanguage;
    }
  }, [currentLanguage, direction]);

  const setLanguage = useCallback((lang: Language) => {
    setCurrentLanguage(lang);
    try {
      localStorage.setItem(STORAGE_KEY, lang);
    } catch (error) {
      console.error('Error saving language preference:', error);
    }
  }, []);

  const t = useCallback((key: string, fallback?: string): string => {
    const translation = translations[currentLanguage]?.[key];
    if (translation) return translation;
    
    // Fallback to English
    const englishTranslation = translations.en[key];
    if (englishTranslation) return englishTranslation;
    
    return fallback || key;
  }, [currentLanguage]);

  const value: LanguageContextType = {
    currentLanguage,
    currentLanguageConfig,
    setLanguage,
    availableLanguages: LANGUAGES,
    isRTL,
    direction,
    t,
    isLoading,
  };

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
