/**
 * PriceX - Global Retailer Configuration
 * Retailers from all regions worldwide
 */

export type DataSourceType = 'scraper' | 'api' | 'feed' | 'manual' | 'affiliate';

export interface RetailerConfig {
  id: string;
  name: string;
  domain: string;
  logo: string;
  website: string;
  region: string;
  country: string;
  currency: string;
  dataSource: DataSourceType;
  apiEndpoint?: string;
  affiliateNetwork?: string;
  rating: number;
  reviewCount: number;
  isVerified: boolean;
  isOfficialStore: boolean;
  shippingInfo: ShippingInfo;
  returnPolicy: ReturnPolicy;
  locations?: RetailerLocation[];
  scraping?: ScrapingConfig;
}

export interface ShippingInfo {
  freeShippingThreshold?: number;
  standardShipping: number;
  expressShipping?: number;
  regions: string[];
  estimatedDelivery?: string;
}

export interface ReturnPolicy {
  allowed: boolean;
  days: number;
  conditions: string;
  restockingFee?: number;
}

export interface RetailerLocation {
  name: string;
  address: string;
  latitude: number;
  longitude: number;
  hours: string;
  phone?: string;
}

export interface ScrapingConfig {
  enabled: boolean;
  rateLimit: number;
  requiresUserAgent: boolean;
  usesCloudflare: boolean;
  captchaRequired: boolean;
}

export const RETAILER_CONFIGS: RetailerConfig[] = [
  // ==================== NORTH AMERICA ====================
  {
    id: 'amazon-us',
    name: 'Amazon US',
    domain: 'amazon.com',
    logo: '/retailers/amazon.svg',
    website: 'https://www.amazon.com',
    region: 'north-america',
    country: 'USA',
    currency: 'USD',
    dataSource: 'api',
    rating: 4.5,
    reviewCount: 50000000,
    isVerified: true,
    isOfficialStore: false,
    shippingInfo: { freeShippingThreshold: 35, standardShipping: 0, expressShipping: 14.99, regions: ['US', 'CA', 'MX'] },
    returnPolicy: { allowed: true, days: 30, conditions: 'Original packaging' },
    scraping: { enabled: false, rateLimit: 1000, requiresUserAgent: true, usesCloudflare: true, captchaRequired: true },
  },
  {
    id: 'amazon-ca',
    name: 'Amazon Canada',
    domain: 'amazon.ca',
    logo: '/retailers/amazon.svg',
    website: 'https://www.amazon.ca',
    region: 'north-america',
    country: 'Canada',
    currency: 'CAD',
    dataSource: 'api',
    rating: 4.4,
    reviewCount: 10000000,
    isVerified: true,
    isOfficialStore: false,
    shippingInfo: { freeShippingThreshold: 35, standardShipping: 0, expressShipping: 9.99, regions: ['CA'] },
    returnPolicy: { allowed: true, days: 30, conditions: 'Original packaging' },
  },
  {
    id: 'bestbuy',
    name: 'Best Buy',
    domain: 'bestbuy.com',
    logo: '/retailers/bestbuy.svg',
    website: 'https://www.bestbuy.com',
    region: 'north-america',
    country: 'USA',
    currency: 'USD',
    dataSource: 'api',
    rating: 4.3,
    reviewCount: 25000000,
    isVerified: true,
    isOfficialStore: false,
    shippingInfo: { freeShippingThreshold: 35, standardShipping: 5.99, expressShipping: 29.99, regions: ['US', 'CA'] },
    returnPolicy: { allowed: true, days: 15, conditions: 'Original packaging' },
  },
  {
    id: 'walmart',
    name: 'Walmart',
    domain: 'walmart.com',
    logo: '/retailers/walmart.svg',
    website: 'https://www.walmart.com',
    region: 'north-america',
    country: 'USA',
    currency: 'USD',
    dataSource: 'api',
    rating: 4.2,
    reviewCount: 30000000,
    isVerified: true,
    isOfficialStore: false,
    shippingInfo: { freeShippingThreshold: 35, standardShipping: 0, regions: ['US'] },
    returnPolicy: { allowed: true, days: 90, conditions: 'Original condition' },
  },
  {
    id: 'target',
    name: 'Target',
    domain: 'target.com',
    logo: '/retailers/target.svg',
    website: 'https://www.target.com',
    region: 'north-america',
    country: 'USA',
    currency: 'USD',
    dataSource: 'api',
    rating: 4.4,
    reviewCount: 20000000,
    isVerified: true,
    isOfficialStore: false,
    shippingInfo: { freeShippingThreshold: 35, standardShipping: 0, regions: ['US'] },
    returnPolicy: { allowed: true, days: 90, conditions: 'Original condition' },
  },
  {
    id: 'ebay',
    name: 'eBay',
    domain: 'ebay.com',
    logo: '/retailers/ebay.svg',
    website: 'https://www.ebay.com',
    region: 'global',
    country: 'USA',
    currency: 'USD',
    dataSource: 'api',
    rating: 4.3,
    reviewCount: 40000000,
    isVerified: true,
    isOfficialStore: false,
    shippingInfo: { standardShipping: 0, regions: ['US', 'CA', 'UK', 'AU', 'DE', 'FR'] },
    returnPolicy: { allowed: true, days: 30, conditions: 'As described' },
  },
  {
    id: 'newegg',
    name: 'Newegg',
    domain: 'newegg.com',
    logo: '/retailers/newegg.svg',
    website: 'https://www.newegg.com',
    region: 'north-america',
    country: 'USA',
    currency: 'USD',
    dataSource: 'api',
    rating: 4.4,
    reviewCount: 15000000,
    isVerified: true,
    isOfficialStore: false,
    shippingInfo: { freeShippingThreshold: 30, standardShipping: 0, regions: ['US', 'CA'] },
    returnPolicy: { allowed: true, days: 30, conditions: 'Original packaging' },
  },
  {
    id: 'homedepot',
    name: 'The Home Depot',
    domain: 'homedepot.com',
    logo: '/retailers/homedepot.svg',
    website: 'https://www.homedepot.com',
    region: 'north-america',
    country: 'USA',
    currency: 'USD',
    dataSource: 'api',
    rating: 4.3,
    reviewCount: 20000000,
    isVerified: true,
    isOfficialStore: false,
    shippingInfo: { freeShippingThreshold: 45, standardShipping: 0, regions: ['US'] },
    returnPolicy: { allowed: true, days: 90, conditions: 'Original receipt' },
  },
  {
    id: 'lowes',
    name: "Lowe's",
    domain: 'lowes.com',
    logo: '/retailers/lowes.svg',
    website: 'https://www.lowes.com',
    region: 'north-america',
    country: 'USA',
    currency: 'USD',
    dataSource: 'api',
    rating: 4.2,
    reviewCount: 15000000,
    isVerified: true,
    isOfficialStore: false,
    shippingInfo: { freeShippingThreshold: 45, standardShipping: 0, regions: ['US'] },
    returnPolicy: { allowed: true, days: 90, conditions: 'Original condition' },
  },
  {
    id: 'costco',
    name: 'Costco',
    domain: 'costco.com',
    logo: '/retailers/costco.svg',
    website: 'https://www.costco.com',
    region: 'north-america',
    country: 'USA',
    currency: 'USD',
    dataSource: 'api',
    rating: 4.5,
    reviewCount: 8000000,
    isVerified: true,
    isOfficialStore: false,
    shippingInfo: { freeShippingThreshold: 0, standardShipping: 0, regions: ['US', 'CA', 'UK'] },
    returnPolicy: { allowed: true, days: 90, conditions: 'Original packaging' },
  },

  // ==================== EUROPE ====================
  {
    id: 'amazon-uk',
    name: 'Amazon UK',
    domain: 'amazon.co.uk',
    logo: '/retailers/amazon.svg',
    website: 'https://www.amazon.co.uk',
    region: 'europe',
    country: 'UK',
    currency: 'GBP',
    dataSource: 'api',
    rating: 4.4,
    reviewCount: 20000000,
    isVerified: true,
    isOfficialStore: false,
    shippingInfo: { freeShippingThreshold: 25, standardShipping: 0, expressShipping: 5.99, regions: ['UK'] },
    returnPolicy: { allowed: true, days: 30, conditions: 'Original packaging' },
  },
  {
    id: 'amazon-de',
    name: 'Amazon Germany',
    domain: 'amazon.de',
    logo: '/retailers/amazon.svg',
    website: 'https://www.amazon.de',
    region: 'europe',
    country: 'Germany',
    currency: 'EUR',
    dataSource: 'api',
    rating: 4.4,
    reviewCount: 25000000,
    isVerified: true,
    isOfficialStore: false,
    shippingInfo: { freeShippingThreshold: 29, standardShipping: 0, expressShipping: 5.99, regions: ['DE', 'AT'] },
    returnPolicy: { allowed: true, days: 30, conditions: 'Original packaging' },
  },
  {
    id: 'amazon-fr',
    name: 'Amazon France',
    domain: 'amazon.fr',
    logo: '/retailers/amazon.svg',
    website: 'https://www.amazon.fr',
    region: 'europe',
    country: 'France',
    currency: 'EUR',
    dataSource: 'api',
    rating: 4.3,
    reviewCount: 15000000,
    isVerified: true,
    isOfficialStore: false,
    shippingInfo: { freeShippingThreshold: 25, standardShipping: 0, regions: ['FR'] },
    returnPolicy: { allowed: true, days: 30, conditions: 'Original packaging' },
  },
  {
    id: 'amazon-es',
    name: 'Amazon Spain',
    domain: 'amazon.es',
    logo: '/retailers/amazon.svg',
    website: 'https://www.amazon.es',
    region: 'europe',
    country: 'Spain',
    currency: 'EUR',
    dataSource: 'api',
    rating: 4.3,
    reviewCount: 8000000,
    isVerified: true,
    isOfficialStore: false,
    shippingInfo: { freeShippingThreshold: 19, standardShipping: 0, regions: ['ES'] },
    returnPolicy: { allowed: true, days: 30, conditions: 'Original packaging' },
  },
  {
    id: 'amazon-it',
    name: 'Amazon Italy',
    domain: 'amazon.it',
    logo: '/retailers/amazon.svg',
    website: 'https://www.amazon.it',
    region: 'europe',
    country: 'Italy',
    currency: 'EUR',
    dataSource: 'api',
    rating: 4.3,
    reviewCount: 7000000,
    isVerified: true,
    isOfficialStore: false,
    shippingInfo: { freeShippingThreshold: 29, standardShipping: 0, regions: ['IT'] },
    returnPolicy: { allowed: true, days: 30, conditions: 'Original packaging' },
  },
  {
    id: 'amazon-nl',
    name: 'Amazon Netherlands',
    domain: 'amazon.nl',
    logo: '/retailers/amazon.svg',
    website: 'https://www.amazon.nl',
    region: 'europe',
    country: 'Netherlands',
    currency: 'EUR',
    dataSource: 'api',
    rating: 4.2,
    reviewCount: 3000000,
    isVerified: true,
    isOfficialStore: false,
    shippingInfo: { freeShippingThreshold: 25, standardShipping: 0, regions: ['NL'] },
    returnPolicy: { allowed: true, days: 30, conditions: 'Original packaging' },
  },
  {
    id: 'amazon-se',
    name: 'Amazon Sweden',
    domain: 'amazon.se',
    logo: '/retailers/amazon.svg',
    website: 'https://www.amazon.se',
    region: 'europe',
    country: 'Sweden',
    currency: 'SEK',
    dataSource: 'api',
    rating: 4.2,
    reviewCount: 2000000,
    isVerified: true,
    isOfficialStore: false,
    shippingInfo: { freeShippingThreshold: 229, standardShipping: 0, regions: ['SE'] },
    returnPolicy: { allowed: true, days: 30, conditions: 'Original packaging' },
  },
  {
    id: 'amazon-pl',
    name: 'Amazon Poland',
    domain: 'amazon.pl',
    logo: '/retailers/amazon.svg',
    website: 'https://www.amazon.pl',
    region: 'europe',
    country: 'Poland',
    currency: 'PLN',
    dataSource: 'api',
    rating: 4.2,
    reviewCount: 4000000,
    isVerified: true,
    isOfficialStore: false,
    shippingInfo: { freeShippingThreshold: 100, standardShipping: 0, regions: ['PL'] },
    returnPolicy: { allowed: true, days: 30, conditions: 'Original packaging' },
  },
  {
    id: 'currys',
    name: 'Currys',
    domain: 'currys.com',
    logo: '/retailers/currys.svg',
    website: 'https://www.currys.com',
    region: 'europe',
    country: 'UK',
    currency: 'GBP',
    dataSource: 'api',
    rating: 4.1,
    reviewCount: 8000000,
    isVerified: true,
    isOfficialStore: false,
    shippingInfo: { freeShippingThreshold: 0, standardShipping: 4.99, regions: ['UK'] },
    returnPolicy: { allowed: true, days: 30, conditions: 'Original packaging' },
  },
  {
    id: 'mediamarkt',
    name: 'MediaMarkt',
    domain: 'mediamarkt.com',
    logo: '/retailers/mediamarkt.svg',
    website: 'https://www.mediamarkt.com',
    region: 'europe',
    country: 'Germany',
    currency: 'EUR',
    dataSource: 'api',
    rating: 4.2,
    reviewCount: 12000000,
    isVerified: true,
    isOfficialStore: false,
    shippingInfo: { freeShippingThreshold: 0, standardShipping: 3.99, regions: ['DE', 'AT', 'NL', 'BE'] },
    returnPolicy: { allowed: true, days: 14, conditions: 'Original packaging' },
  },
  {
    id: 'saturn',
    name: 'Saturn',
    domain: 'saturn.com',
    logo: '/retailers/saturn.svg',
    website: 'https://www.saturn.com',
    region: 'europe',
    country: 'Germany',
    currency: 'EUR',
    dataSource: 'api',
    rating: 4.1,
    reviewCount: 5000000,
    isVerified: true,
    isOfficialStore: false,
    shippingInfo: { freeShippingThreshold: 0, standardShipping: 3.99, regions: ['DE'] },
    returnPolicy: { allowed: true, days: 14, conditions: 'Original packaging' },
  },
  {
    id: 'fnac',
    name: 'Fnac',
    domain: 'fnac.com',
    logo: '/retailers/fnac.svg',
    website: 'https://www.fnac.com',
    region: 'europe',
    country: 'France',
    currency: 'EUR',
    dataSource: 'api',
    rating: 4.2,
    reviewCount: 6000000,
    isVerified: true,
    isOfficialStore: false,
    shippingInfo: { freeShippingThreshold: 20, standardShipping: 0, regions: ['FR', 'BE', 'ES'] },
    returnPolicy: { allowed: true, days: 30, conditions: 'Original packaging' },
  },
  {
    id: 'elcorteingles',
    name: 'El Corte Inglés',
    domain: 'elcorteingles.com',
    logo: '/retailers/elcorteingles.svg',
    website: 'https://www.elcorteingles.com',
    region: 'europe',
    country: 'Spain',
    currency: 'EUR',
    dataSource: 'api',
    rating: 4.2,
    reviewCount: 5000000,
    isVerified: true,
    isOfficialStore: false,
    shippingInfo: { freeShippingThreshold: 30, standardShipping: 0, regions: ['ES'] },
    returnPolicy: { allowed: true, days: 30, conditions: 'Original packaging' },
  },
  {
    id: 'gigantti',
    name: 'Gigantti',
    domain: 'gigantti.com',
    logo: '/retailers/gigantti.svg',
    website: 'https://www.gigantti.com',
    region: 'europe',
    country: 'Finland',
    currency: 'EUR',
    dataSource: 'api',
    rating: 4.1,
    reviewCount: 1000000,
    isVerified: true,
    isOfficialStore: false,
    shippingInfo: { freeShippingThreshold: 0, standardShipping: 4.90, regions: ['FI'] },
    returnPolicy: { allowed: true, days: 14, conditions: 'Original packaging' },
  },

  // ==================== ASIA PACIFIC ====================
  {
    id: 'amazon-jp',
    name: 'Amazon Japan',
    domain: 'amazon.co.jp',
    logo: '/retailers/amazon.svg',
    website: 'https://www.amazon.co.jp',
    region: 'asia',
    country: 'Japan',
    currency: 'JPY',
    dataSource: 'api',
    rating: 4.3,
    reviewCount: 20000000,
    isVerified: true,
    isOfficialStore: false,
    shippingInfo: { freeShippingThreshold: 2000, standardShipping: 0, regions: ['JP'] },
    returnPolicy: { allowed: true, days: 30, conditions: 'Original packaging' },
  },
  {
    id: 'amazon-in',
    name: 'Amazon India',
    domain: 'amazon.in',
    logo: '/retailers/amazon.svg',
    website: 'https://www.amazon.in',
    region: 'asia',
    country: 'India',
    currency: 'INR',
    dataSource: 'api',
    rating: 4.2,
    reviewCount: 30000000,
    isVerified: true,
    isOfficialStore: false,
    shippingInfo: { freeShippingThreshold: 499, standardShipping: 0, regions: ['IN'] },
    returnPolicy: { allowed: true, days: 10, conditions: 'Original packaging' },
  },
  {
    id: 'amazon-sg',
    name: 'Amazon Singapore',
    domain: 'amazon.sg',
    logo: '/retailers/amazon.svg',
    website: 'https://www.amazon.sg',
    region: 'asia',
    country: 'Singapore',
    currency: 'SGD',
    dataSource: 'api',
    rating: 4.3,
    reviewCount: 2000000,
    isVerified: true,
    isOfficialStore: false,
    shippingInfo: { freeShippingThreshold: 40, standardShipping: 0, regions: ['SG'] },
    returnPolicy: { allowed: true, days: 30, conditions: 'Original packaging' },
  },
  {
    id: 'amazon-au',
    name: 'Amazon Australia',
    domain: 'amazon.com.au',
    logo: '/retailers/amazon.svg',
    website: 'https://www.amazon.com.au',
    region: 'oceania',
    country: 'Australia',
    currency: 'AUD',
    dataSource: 'api',
    rating: 4.2,
    reviewCount: 5000000,
    isVerified: true,
    isOfficialStore: false,
    shippingInfo: { freeShippingThreshold: 35, standardShipping: 0, regions: ['AU'] },
    returnPolicy: { allowed: true, days: 30, conditions: 'Original packaging' },
  },
  {
    id: 'rakuten',
    name: 'Rakuten',
    domain: 'rakuten.com',
    logo: '/retailers/rakuten.svg',
    website: 'https://www.rakuten.com',
    region: 'asia',
    country: 'Japan',
    currency: 'USD',
    dataSource: 'api',
    rating: 4.1,
    reviewCount: 8000000,
    isVerified: true,
    isOfficialStore: false,
    shippingInfo: { freeShippingThreshold: 35, standardShipping: 0, regions: ['US', 'JP'] },
    returnPolicy: { allowed: true, days: 30, conditions: 'Original packaging' },
  },
  {
    id: 'alibaba',
    name: 'Alibaba',
    domain: 'alibaba.com',
    logo: '/retailers/alibaba.svg',
    website: 'https://www.alibaba.com',
    region: 'asia',
    country: 'China',
    currency: 'USD',
    dataSource: 'api',
    rating: 4.0,
    reviewCount: 50000000,
    isVerified: true,
    isOfficialStore: false,
    shippingInfo: { freeShippingThreshold: 0, standardShipping: 0, regions: ['CN', 'US', 'EU'] },
    returnPolicy: { allowed: true, days: 15, conditions: 'As described' },
  },
  {
    id: 'aliexpress',
    name: 'AliExpress',
    domain: 'aliexpress.com',
    logo: '/retailers/aliexpress.svg',
    website: 'https://www.aliexpress.com',
    region: 'global',
    country: 'China',
    currency: 'USD',
    dataSource: 'api',
    rating: 4.0,
    reviewCount: 100000000,
    isVerified: true,
    isOfficialStore: false,
    shippingInfo: { freeShippingThreshold: 0, standardShipping: 0, regions: ['CN', 'US', 'EU', 'RU'] },
    returnPolicy: { allowed: true, days: 15, conditions: 'Not opened' },
  },
  {
    id: 'jd',
    name: 'JD.com',
    domain: 'jd.com',
    logo: '/retailers/jd.svg',
    website: 'https://www.jd.com',
    region: 'asia',
    country: 'China',
    currency: 'CNY',
    dataSource: 'api',
    rating: 4.3,
    reviewCount: 60000000,
    isVerified: true,
    isOfficialStore: false,
    shippingInfo: { freeShippingThreshold: 99, standardShipping: 0, regions: ['CN'] },
    returnPolicy: { allowed: true, days: 30, conditions: 'Original packaging' },
  },
  {
    id: 'flipkart',
    name: 'Flipkart',
    domain: 'flipkart.com',
    logo: '/retailers/flipkart.svg',
    website: 'https://www.flipkart.com',
    region: 'asia',
    country: 'India',
    currency: 'INR',
    dataSource: 'api',
    rating: 4.2,
    reviewCount: 40000000,
    isVerified: true,
    isOfficialStore: false,
    shippingInfo: { freeShippingThreshold: 500, standardShipping: 0, regions: ['IN'] },
    returnPolicy: { allowed: true, days: 10, conditions: 'Original packaging' },
  },
  {
    id: 'shopee',
    name: 'Shopee',
    domain: 'shopee.com',
    logo: '/retailers/shopee.svg',
    website: 'https://www.shopee.com',
    region: 'asia',
    country: 'Singapore',
    currency: 'SGD',
    dataSource: 'api',
    rating: 4.1,
    reviewCount: 30000000,
    isVerified: true,
    isOfficialStore: false,
    shippingInfo: { freeShippingThreshold: 0, standardShipping: 0, regions: ['SG', 'MY', 'PH', 'TH', 'VN', 'ID'] },
    returnPolicy: { allowed: true, days: 15, conditions: 'Original packaging' },
  },
  {
    id: 'lazada',
    name: 'Lazada',
    domain: 'lazada.com',
    logo: '/retailers/lazada.svg',
    website: 'https://www.lazada.com',
    region: 'asia',
    country: 'Singapore',
    currency: 'SGD',
    dataSource: 'api',
    rating: 4.1,
    reviewCount: 20000000,
    isVerified: true,
    isOfficialStore: false,
    shippingInfo: { freeShippingThreshold: 0, standardShipping: 0, regions: ['SG', 'MY', 'PH', 'TH', 'VN', 'ID'] },
    returnPolicy: { allowed: true, days: 15, conditions: 'Original packaging' },
  },
  {
    id: 'b&h',
    name: 'B&H Photo',
    domain: 'bhphotovideo.com',
    logo: '/retailers/bh.svg',
    website: 'https://www.bhphotovideo.com',
    region: 'north-america',
    country: 'USA',
    currency: 'USD',
    dataSource: 'api',
    rating: 4.5,
    reviewCount: 5000000,
    isVerified: true,
    isOfficialStore: false,
    shippingInfo: { freeShippingThreshold: 49, standardShipping: 0, regions: ['US'] },
    returnPolicy: { allowed: true, days: 30, conditions: 'Original packaging' },
  },
  {
    id: 'kogan',
    name: 'Kogan',
    domain: 'kogan.com',
    logo: '/retailers/kogan.svg',
    website: 'https://www.kogan.com',
    region: 'oceania',
    country: 'Australia',
    currency: 'AUD',
    dataSource: 'api',
    rating: 4.0,
    reviewCount: 3000000,
    isVerified: true,
    isOfficialStore: false,
    shippingInfo: { freeShippingThreshold: 0, standardShipping: 5.99, regions: ['AU', 'NZ'] },
    returnPolicy: { allowed: true, days: 30, conditions: 'Original packaging' },
  },
  {
    id: 'jb-hi-fi',
    name: 'JB Hi-Fi',
    domain: 'jbhifi.com.au',
    logo: '/retailers/jb-hi-fi.svg',
    website: 'https://www.jbhifi.com.au',
    region: 'oceania',
    country: 'Australia',
    currency: 'AUD',
    dataSource: 'api',
    rating: 4.3,
    reviewCount: 4000000,
    isVerified: true,
    isOfficialStore: false,
    shippingInfo: { freeShippingThreshold: 0, standardShipping: 5.95, regions: ['AU'] },
    returnPolicy: { allowed: true, days: 14, conditions: 'Original packaging' },
  },

  // ==================== MIDDLE EAST ====================
  {
    id: 'amazon-ae',
    name: 'Amazon UAE',
    domain: 'amazon.ae',
    logo: '/retailers/amazon.svg',
    website: 'https://www.amazon.ae',
    region: 'middle-east',
    country: 'UAE',
    currency: 'AED',
    dataSource: 'api',
    rating: 4.3,
    reviewCount: 3000000,
    isVerified: true,
    isOfficialStore: false,
    shippingInfo: { freeShippingThreshold: 100, standardShipping: 0, regions: ['UAE', 'SA', 'KW', 'EG'] },
    returnPolicy: { allowed: true, days: 14, conditions: 'Original packaging' },
  },
  {
    id: 'amazon-sa',
    name: 'Amazon Saudi',
    domain: 'amazon.sa',
    logo: '/retailers/amazon.svg',
    website: 'https://www.amazon.sa',
    region: 'middle-east',
    country: 'Saudi Arabia',
    currency: 'SAR',
    dataSource: 'api',
    rating: 4.3,
    reviewCount: 2000000,
    isVerified: true,
    isOfficialStore: false,
    shippingInfo: { freeShippingThreshold: 100, standardShipping: 0, regions: ['SA', 'UAE'] },
    returnPolicy: { allowed: true, days: 14, conditions: 'Original packaging' },
  },
  {
    id: 'noon',
    name: 'Noon',
    domain: 'noon.com',
    logo: '/retailers/noon.svg',
    website: 'https://www.noon.com',
    region: 'middle-east',
    country: 'UAE',
    currency: 'AED',
    dataSource: 'api',
    rating: 4.1,
    reviewCount: 8000000,
    isVerified: true,
    isOfficialStore: false,
    shippingInfo: { freeShippingThreshold: 100, standardShipping: 0, regions: ['UAE', 'SA', 'EG', 'KW'] },
    returnPolicy: { allowed: true, days: 14, conditions: 'Original packaging' },
  },
  {
    id: 'jarir',
    name: 'Jarir Bookstore',
    domain: 'jarir.com',
    logo: '/retailers/jarir.svg',
    website: 'https://www.jarir.com',
    region: 'middle-east',
    country: 'Saudi Arabia',
    currency: 'SAR',
    dataSource: 'api',
    rating: 4.2,
    reviewCount: 2000000,
    isVerified: true,
    isOfficialStore: false,
    shippingInfo: { freeShippingThreshold: 0, standardShipping: 15, regions: ['SA', 'UAE', 'KW'] },
    returnPolicy: { allowed: true, days: 14, conditions: 'Original packaging' },
  },
  {
    id: 'extra',
    name: 'Extra.com',
    domain: 'extra.com',
    logo: '/retailers/extra.svg',
    website: 'https://www.extra.com',
    region: 'middle-east',
    country: 'Saudi Arabia',
    currency: 'SAR',
    dataSource: 'api',
    rating: 4.0,
    reviewCount: 1000000,
    isVerified: true,
    isOfficialStore: false,
    shippingInfo: { freeShippingThreshold: 0, standardShipping: 20, regions: ['SA'] },
    returnPolicy: { allowed: true, days: 14, conditions: 'Original packaging' },
  },

  // ==================== SOUTH AMERICA ====================
  {
    id: 'amazon-br',
    name: 'Amazon Brazil',
    domain: 'amazon.com.br',
    logo: '/retailers/amazon.svg',
    website: 'https://www.amazon.com.br',
    region: 'south-america',
    country: 'Brazil',
    currency: 'BRL',
    dataSource: 'api',
    rating: 4.2,
    reviewCount: 15000000,
    isVerified: true,
    isOfficialStore: false,
    shippingInfo: { freeShippingThreshold: 100, standardShipping: 0, regions: ['BR'] },
    returnPolicy: { allowed: true, days: 30, conditions: 'Original packaging' },
  },
  {
    id: 'amazon-mx',
    name: 'Amazon Mexico',
    domain: 'amazon.com.mx',
    logo: '/retailers/amazon.svg',
    website: 'https://www.amazon.com.mx',
    region: 'north-america',
    country: 'Mexico',
    currency: 'MXN',
    dataSource: 'api',
    rating: 4.2,
    reviewCount: 8000000,
    isVerified: true,
    isOfficialStore: false,
    shippingInfo: { freeShippingThreshold: 500, standardShipping: 0, regions: ['MX'] },
    returnPolicy: { allowed: true, days: 30, conditions: 'Original packaging' },
  },
  {
    id: 'mercadolibre',
    name: 'Mercado Libre',
    domain: 'mercadolibre.com',
    logo: '/retailers/mercadolibre.svg',
    website: 'https://www.mercadolibre.com',
    region: 'south-america',
    country: 'Argentina',
    currency: 'ARS',
    dataSource: 'api',
    rating: 4.1,
    reviewCount: 50000000,
    isVerified: true,
    isOfficialStore: false,
    shippingInfo: { freeShippingThreshold: 0, standardShipping: 0, regions: ['AR', 'MX', 'CO', 'CL', 'PE'] },
    returnPolicy: { allowed: true, days: 30, conditions: 'As described' },
  },
  {
    id: 'magazineluiza',
    name: 'Magazine Luiza',
    domain: 'magazineluiza.com.br',
    logo: '/retailers/magazineluiza.svg',
    website: 'https://www.magazineluiza.com.br',
    region: 'south-america',
    country: 'Brazil',
    currency: 'BRL',
    dataSource: 'api',
    rating: 4.2,
    reviewCount: 20000000,
    isVerified: true,
    isOfficialStore: false,
    shippingInfo: { freeShippingThreshold: 199, standardShipping: 0, regions: ['BR'] },
    returnPolicy: { allowed: true, days: 30, conditions: 'Original packaging' },
  },
  {
    id: 'linio',
    name: 'Linio',
    domain: 'linio.com',
    logo: '/retailers/linio.svg',
    website: 'https://www.linio.com',
    region: 'south-america',
    country: 'Colombia',
    currency: 'COP',
    dataSource: 'api',
    rating: 4.0,
    reviewCount: 5000000,
    isVerified: true,
    isOfficialStore: false,
    shippingInfo: { freeShippingThreshold: 0, standardShipping: 0, regions: ['CO', 'MX', 'CL', 'PE'] },
    returnPolicy: { allowed: true, days: 30, conditions: 'Original packaging' },
  },

  // ==================== AFRICA ====================
  {
    id: 'jumia',
    name: 'Jumia',
    domain: 'jumia.com',
    logo: '/retailers/jumia.svg',
    website: 'https://www.jumia.com',
    region: 'africa',
    country: 'Nigeria',
    currency: 'NGN',
    dataSource: 'api',
    rating: 4.0,
    reviewCount: 10000000,
    isVerified: true,
    isOfficialStore: false,
    shippingInfo: { freeShippingThreshold: 0, standardShipping: 0, regions: ['NG', 'KE', 'GH', 'EG', 'ZA'] },
    returnPolicy: { allowed: true, days: 7, conditions: 'Original packaging' },
  },
  {
    id: 'takealot',
    name: 'Takealot',
    domain: 'takealot.com',
    logo: '/retailers/takealot.svg',
    website: 'https://www.takealot.com',
    region: 'africa',
    country: 'South Africa',
    currency: 'ZAR',
    dataSource: 'api',
    rating: 4.1,
    reviewCount: 5000000,
    isVerified: true,
    isOfficialStore: false,
    shippingInfo: { freeShippingThreshold: 500, standardShipping: 0, regions: ['ZA'] },
    returnPolicy: { allowed: true, days: 30, conditions: 'Original packaging' },
  },
  {
    id: 'konga',
    name: 'Konga',
    domain: 'konga.com',
    logo: '/retailers/konga.svg',
    website: 'https://www.konga.com',
    region: 'africa',
    country: 'Nigeria',
    currency: 'NGN',
    dataSource: 'api',
    rating: 3.9,
    reviewCount: 3000000,
    isVerified: true,
    isOfficialStore: false,
    shippingInfo: { freeShippingThreshold: 0, standardShipping: 0, regions: ['NG'] },
    returnPolicy: { allowed: true, days: 7, conditions: 'Original packaging' },
  },
];

export function getRetailerConfig(retailerId: string): RetailerConfig | undefined {
  return RETAILER_CONFIGS.find(r => r.id === retailerId);
}

export function getRetailersByRegion(region: string): RetailerConfig[] {
  return RETAILER_CONFIGS.filter(r => r.region === region || r.region === 'global');
}

export function getRetailersByCountry(country: string): RetailerConfig[] {
  return RETAILER_CONFIGS.filter(r => r.country.toLowerCase() === country.toLowerCase());
}

export function getAllRegions(): string[] {
  return ['north-america', 'europe', 'asia', 'middle-east', 'south-america', 'africa', 'oceania', 'global'];
}

export function getAllCountries(): string[] {
  return [...new Set(RETAILER_CONFIGS.map(r => r.country))];
}

export function getRegionName(region: string): string {
  const regionNames: Record<string, string> = {
    'north-america': 'North America',
    'europe': 'Europe',
    'asia': 'Asia Pacific',
    'middle-east': 'Middle East',
    'south-america': 'South America',
    'africa': 'Africa',
    'oceania': 'Oceania',
    'global': 'Worldwide',
  };
  return regionNames[region] || region;
}
