/**
 * PriceX - Global Product Sample Data
 * Products with retailers from all regions worldwide
 */

import { Product } from '@/types/product-data';
import { getCategoryById } from '@/types/product';
import { getRetailerConfig } from './retailer-config';

// Helper to get retailer data from config
const getRetailer = (id: string) => {
  const config = getRetailerConfig(id);
  if (!config) return null;
  return {
    id: config.id,
    name: config.name,
    logo: config.logo,
    website: config.website,
    region: config.region,
    rating: config.rating,
    reviewCount: config.reviewCount,
    isVerified: config.isVerified,
    isOfficialStore: config.isOfficialStore,
    shippingInfo: config.shippingInfo,
    returnPolicy: config.returnPolicy,
    locations: config.locations || [],
  };
};

export const GLOBAL_SAMPLE_PRODUCTS: Product[] = [
  {
    id: '1',
    name: 'iPhone 15 Pro Max',
    description: 'The most advanced iPhone with A17 Pro chip, titanium design, and 48MP camera system.',
    brand: 'Apple',
    model: 'iPhone 15 Pro Max',
    sku: 'MU783LL/A',
    mpn: 'MU783LL/A',
    upc: '195949147046',
    categoryId: 'electronics',
    category: getCategoryById('electronics')!,
    images: [
      { id: '1', url: '/product-1.jpg', thumbnail: '/product-1.jpg', alt: 'iPhone 15 Pro Max', type: 'main', order: 1 },
    ],
    specifications: [
      { attributeId: 'display', name: 'Display', value: '6.7" Super Retina XDR', group: 'Display' },
      { attributeId: 'chip', name: 'Chip', value: 'A17 Pro', group: 'Performance' },
      { attributeId: 'camera', name: 'Camera', value: '48MP Main + 12MP Ultra Wide + 12MP Telephoto', group: 'Camera' },
    ],
    attributes: { screen_size: 6.7, storage: '256GB', color: 'Natural Titanium', brand: 'Apple' },
    pricePoints: [
      {
        id: 'pp1', retailerId: 'amazon-us', retailer: getRetailer('amazon-us')!,
        price: 1199, originalPrice: 1299, currency: 'USD', availability: 'in_stock', condition: 'new', url: 'https://amazon.com/iphone15pro', sku: 'B0CHX1W1XY', shippingCost: 0, shippingTime: '1-2 days', isOfficialStore: false, warranty: '1 year Apple warranty', inStock: true, stockQuantity: 150, discountPercent: 8, lastUpdated: new Date(),
      },
      {
        id: 'pp2', retailerId: 'bestbuy', retailer: getRetailer('bestbuy')!,
        price: 1199, originalPrice: 1299, currency: 'USD', availability: 'in_stock', condition: 'new', url: 'https://bestbuy.com/iphone15pro', sku: '6418599', shippingCost: 0, shippingTime: 'Same day', isOfficialStore: false, warranty: '1 year Apple warranty', inStock: true, stockQuantity: 89, discountPercent: 8, lastUpdated: new Date(),
      },
      {
        id: 'pp3', retailerId: 'amazon-uk', retailer: getRetailer('amazon-uk')!,
        price: 1099, originalPrice: 1199, currency: 'GBP', availability: 'in_stock', condition: 'new', url: 'https://amazon.co.uk/iphone15pro', sku: 'B0CHX1W1XY', shippingCost: 0, shippingTime: '2-3 days', isOfficialStore: false, warranty: '1 year Apple warranty', inStock: true, stockQuantity: 200, discountPercent: 8, lastUpdated: new Date(),
      },
      {
        id: 'pp4', retailerId: 'amazon-de', retailer: getRetailer('amazon-de')!,
        price: 1149, originalPrice: 1249, currency: 'EUR', availability: 'in_stock', condition: 'new', url: 'https://amazon.de/iphone15pro', sku: 'B0CHX1W1XY', shippingCost: 0, shippingTime: '2-5 days', isOfficialStore: false, warranty: '1 year Apple warranty', inStock: true, stockQuantity: 120, discountPercent: 8, lastUpdated: new Date(),
      },
      {
        id: 'pp5', retailerId: 'amazon-jp', retailer: getRetailer('amazon-jp')!,
        price: 178000, originalPrice: 198000, currency: 'JPY', availability: 'in_stock', condition: 'new', url: 'https://amazon.co.jp/iphone15pro', sku: 'B0CHX1W1XY', shippingCost: 0, shippingTime: '1-3 days', isOfficialStore: false, warranty: '1 year Apple warranty', inStock: true, stockQuantity: 300, discountPercent: 10, lastUpdated: new Date(),
      },
      {
        id: 'pp6', retailerId: 'amazon-in', retailer: getRetailer('amazon-in')!,
        price: 99900, originalPrice: 109900, currency: 'INR', availability: 'in_stock', condition: 'new', url: 'https://amazon.in/iphone15pro', sku: 'B0CHX1W1XY', shippingCost: 0, shippingTime: '2-5 days', isOfficialStore: false, warranty: '1 year Apple warranty', inStock: true, stockQuantity: 80, discountPercent: 9, lastUpdated: new Date(),
      },
      {
        id: 'pp7', retailerId: 'amazon-ae', retailer: getRetailer('amazon-ae')!,
        price: 4399, originalPrice: 4799, currency: 'AED', availability: 'in_stock', condition: 'new', url: 'https://amazon.ae/iphone15pro', sku: 'B0CHX1W1XY', shippingCost: 0, shippingTime: '2-4 days', isOfficialStore: false, warranty: '1 year Apple warranty', inStock: true, stockQuantity: 60, discountPercent: 8, lastUpdated: new Date(),
      },
      {
        id: 'pp8', retailerId: 'amazon-au', retailer: getRetailer('amazon-au')!,
        price: 1849, originalPrice: 1999, currency: 'AUD', availability: 'in_stock', condition: 'new', url: 'https://amazon.com.au/iphone15pro', sku: 'B0CHX1W1XY', shippingCost: 0, shippingTime: '3-5 days', isOfficialStore: false, warranty: '1 year Apple warranty', inStock: true, stockQuantity: 100, discountPercent: 8, lastUpdated: new Date(),
      },
      {
        id: 'pp9', retailerId: 'amazon-br', retailer: getRetailer('amazon-br')!,
        price: 5999, originalPrice: 6499, currency: 'BRL', availability: 'in_stock', condition: 'new', url: 'https://amazon.com.br/iphone15pro', sku: 'B0CHX1W1XY', shippingCost: 0, shippingTime: '5-7 days', isOfficialStore: false, warranty: '1 year Apple warranty', inStock: true, stockQuantity: 50, discountPercent: 8, lastUpdated: new Date(),
      },
      {
        id: 'pp10', retailerId: 'ebay', retailer: getRetailer('ebay')!,
        price: 1149, originalPrice: 1299, currency: 'USD', availability: 'in_stock', condition: 'new', url: 'https://ebay.com/iphone15pro', sku: 'B0CHX1W1XY', shippingCost: 0, shippingTime: '3-5 days', isOfficialStore: false, warranty: '1 year Apple warranty', inStock: true, stockQuantity: 75, discountPercent: 12, lastUpdated: new Date(),
      },
    ],
    priceRange: { min: 1099, max: 5999, currency: 'USD' },
    rating: 4.8, reviewCount: 2543, availability: 'in_stock', condition: 'new',
    features: ['A17 Pro chip', 'Titanium design', '48MP camera', 'Action button', 'USB-C'],
    tags: ['smartphone', 'flagship', 'ios', '5g'], isVerified: true, verifiedAt: new Date(),
    seo: { title: 'iPhone 15 Pro Max - Compare Prices', description: 'Compare iPhone 15 Pro Max prices from trusted retailers worldwide', keywords: ['iphone', 'apple', 'smartphone'] },
    createdAt: new Date('2023-09-01'), updatedAt: new Date(),
  },
  {
    id: '2',
    name: 'Samsung Galaxy S24 Ultra',
    description: 'Premium Android smartphone with S Pen, 200MP camera, and AI features.',
    brand: 'Samsung',
    model: 'Galaxy S24 Ultra',
    sku: 'SM-S928BZKE',
    categoryId: 'electronics',
    category: getCategoryById('electronics')!,
    images: [{ id: '1', url: '/product-2.jpg', thumbnail: '/product-2.jpg', alt: 'Samsung Galaxy S24 Ultra', type: 'main', order: 1 }],
    specifications: [
      { attributeId: 'display', name: 'Display', value: '6.8" Dynamic AMOLED', group: 'Display' },
      { attributeId: 'chip', name: 'Chip', value: 'Snapdragon 8 Gen 3', group: 'Performance' },
    ],
    attributes: { screen_size: 6.8, storage: '512GB', color: 'Titanium Black', brand: 'Samsung' },
    pricePoints: [
      {
        id: 'pp1', retailerId: 'amazon-us', retailer: getRetailer('amazon-us')!,
        price: 1299, originalPrice: 1399, currency: 'USD', availability: 'in_stock', condition: 'new', url: 'https://amazon.com/galaxy-s24', sku: 'B0CQJJBDW5', shippingCost: 0, shippingTime: '1-2 days', isOfficialStore: false, warranty: '1 year Samsung warranty', inStock: true, stockQuantity: 200, discountPercent: 7, lastUpdated: new Date(),
      },
      {
        id: 'pp2', retailerId: 'amazon-uk', retailer: getRetailer('amazon-uk')!,
        price: 1199, originalPrice: 1299, currency: 'GBP', availability: 'in_stock', condition: 'new', url: 'https://amazon.co.uk/galaxy-s24', sku: 'B0CQJJBDW5', shippingCost: 0, shippingTime: '2-3 days', isOfficialStore: false, warranty: '1 year Samsung warranty', inStock: true, stockQuantity: 150, discountPercent: 8, lastUpdated: new Date(),
      },
      {
        id: 'pp3', retailerId: 'amazon-de', retailer: getRetailer('amazon-de')!,
        price: 1249, originalPrice: 1349, currency: 'EUR', availability: 'in_stock', condition: 'new', url: 'https://amazon.de/galaxy-s24', sku: 'B0CQJJBDW5', shippingCost: 0, shippingTime: '2-5 days', isOfficialStore: false, warranty: '1 year Samsung warranty', inStock: true, stockQuantity: 100, discountPercent: 7, lastUpdated: new Date(),
      },
      {
        id: 'pp4', retailerId: 'flipkart', retailer: getRetailer('flipkart')!,
        price: 99999, originalPrice: 109999, currency: 'INR', availability: 'in_stock', condition: 'new', url: 'https://flipkart.com/galaxy-s24', sku: 'B0CQJJBDW5', shippingCost: 0, shippingTime: '2-4 days', isOfficialStore: false, warranty: '1 year Samsung warranty', inStock: true, stockQuantity: 80, discountPercent: 9, lastUpdated: new Date(),
      },
      {
        id: 'pp5', retailerId: 'noon', retailer: getRetailer('noon')!,
        price: 4799, originalPrice: 5199, currency: 'AED', availability: 'in_stock', condition: 'new', url: 'https://noon.com/galaxy-s24', sku: 'B0CQJJBDW5', shippingCost: 0, shippingTime: '2-3 days', isOfficialStore: false, warranty: '1 year Samsung warranty', inStock: true, stockQuantity: 50, discountPercent: 8, lastUpdated: new Date(),
      },
    ],
    priceRange: { min: 1299, max: 99999, currency: 'USD' },
    rating: 4.7, reviewCount: 1823, availability: 'in_stock', condition: 'new',
    features: ['S Pen', '200MP camera', 'AI features', 'Titanium frame', '5G'], tags: ['smartphone', 'android', 'samsung'], isVerified: true, verifiedAt: new Date(),
    seo: { title: 'Samsung Galaxy S24 Ultra - Compare Prices', description: 'Compare Galaxy S24 Ultra prices from worldwide retailers', keywords: ['samsung', 'galaxy', 'smartphone'] },
    createdAt: new Date('2024-01-01'), updatedAt: new Date(),
  },
  {
    id: '3',
    name: 'MacBook Pro 16" M3 Max',
    description: 'Powerful laptop with M3 Max chip, Liquid Retina XDR display, up to 22 hours battery.',
    brand: 'Apple',
    model: 'MacBook Pro 16"',
    sku: 'MX2E3LL/A',
    categoryId: 'electronics',
    category: getCategoryById('electronics')!,
    images: [{ id: '1', url: '/product-3.jpg', thumbnail: '/product-3.jpg', alt: 'MacBook Pro 16"', type: 'main', order: 1 }],
    specifications: [
      { attributeId: 'display', name: 'Display', value: '16.2" Liquid Retina XDR', group: 'Display' },
      { attributeId: 'chip', name: 'Chip', value: 'M3 Max', group: 'Performance' },
    ],
    attributes: { screen_size: 16.2, storage: '1TB', color: 'Space Black', brand: 'Apple' },
    pricePoints: [
      {
        id: 'pp1', retailerId: 'amazon-us', retailer: getRetailer('amazon-us')!,
        price: 3499, originalPrice: 3499, currency: 'USD', availability: 'in_stock', condition: 'new', url: 'https://amazon.com/macbook-pro', sku: 'B0CM5JV268', shippingCost: 0, shippingTime: '2-3 days', isOfficialStore: false, warranty: '1 year Apple warranty', inStock: true, stockQuantity: 50, lastUpdated: new Date(),
      },
      {
        id: 'pp2', retailerId: 'bestbuy', retailer: getRetailer('bestbuy')!,
        price: 3499, originalPrice: 3499, currency: 'USD', availability: 'in_stock', condition: 'new', url: 'https://bestbuy.com/macbook-pro', sku: 'B0CM5JV268', shippingCost: 0, shippingTime: 'Same day', isOfficialStore: false, warranty: '1 year Apple warranty', inStock: true, stockQuantity: 30, lastUpdated: new Date(),
      },
      {
        id: 'pp3', retailerId: 'currys', retailer: getRetailer('currys')!,
        price: 2999, originalPrice: 3199, currency: 'GBP', availability: 'in_stock', condition: 'new', url: 'https://currys.com/macbook-pro', sku: 'B0CM5JV268', shippingCost: 0, shippingTime: '2-4 days', isOfficialStore: false, warranty: '1 year Apple warranty', inStock: true, stockQuantity: 20, discountPercent: 6, lastUpdated: new Date(),
      },
      {
        id: 'pp4', retailerId: 'mediamarkt', retailer: getRetailer('mediamarkt')!,
        price: 3299, originalPrice: 3499, currency: 'EUR', availability: 'in_stock', condition: 'new', url: 'https://mediamarkt.com/macbook-pro', sku: 'B0CM5JV268', shippingCost: 0, shippingTime: '2-3 days', isOfficialStore: false, warranty: '1 year Apple warranty', inStock: true, stockQuantity: 25, discountPercent: 6, lastUpdated: new Date(),
      },
    ],
    priceRange: { min: 2999, max: 3499, currency: 'USD' },
    rating: 4.9, reviewCount: 956, availability: 'in_stock', condition: 'new',
    features: ['M3 Max chip', 'Liquid Retina XDR', '36GB RAM', '1TB SSD'], tags: ['laptop', 'apple', 'macbook'], isVerified: true, verifiedAt: new Date(),
    seo: { title: 'MacBook Pro 16" M3 Max - Compare Prices', description: 'Compare MacBook Pro prices from global retailers', keywords: ['macbook', 'apple', 'laptop'] },
    createdAt: new Date('2023-10-01'), updatedAt: new Date(),
  },
  // More Electronics
  {
    id: '13',
    name: 'Sony PlayStation 5 Pro',
    description: 'Next-gen gaming console with enhanced graphics and 2TB SSD.',
    brand: 'Sony',
    model: 'PS5 Pro',
    sku: 'CFI-7000',
    categoryId: 'electronics',
    category: getCategoryById('electronics')!,
    images: [{ id: '1', url: '/product-10.jpg', thumbnail: '/product-10.jpg', alt: 'PS5 Pro', type: 'main', order: 1 }],
    specifications: [{ attributeId: 'storage', name: 'Storage', value: '2TB SSD', group: 'Storage' }],
    attributes: { storage: '2TB', color: 'White', brand: 'Sony' },
    pricePoints: [
      { id: 'pp1', retailerId: 'amazon-us', retailer: getRetailer('amazon-us')!, price: 699, originalPrice: 699, currency: 'USD', availability: 'in_stock', condition: 'new', url: 'https://amazon.com/ps5-pro', shippingCost: 0, shippingTime: '2-3 days', inStock: true, stockQuantity: 100, lastUpdated: new Date() },
      { id: 'pp2', retailerId: 'bestbuy', retailer: getRetailer('bestbuy')!, price: 699, originalPrice: 749, currency: 'USD', availability: 'in_stock', condition: 'new', url: 'https://bestbuy.com/ps5-pro', shippingCost: 0, shippingTime: 'Same day', inStock: true, stockQuantity: 50, discountPercent: 7, lastUpdated: new Date() },
    ],
    priceRange: { min: 699, max: 749, currency: 'USD' },
    rating: 4.9, reviewCount: 15000, availability: 'in_stock', condition: 'new',
    features: ['2TB SSD', '4K Gaming', 'Ray Tracing'], tags: ['gaming', 'playstation', 'sony'], isVerified: true, verifiedAt: new Date(),
    seo: { title: 'PS5 Pro - Compare Prices', description: 'Compare PS5 Pro prices', keywords: ['ps5', 'playstation', 'gaming'] },
    createdAt: new Date('2024-01-01'), updatedAt: new Date(),
  },
  {
    id: '14',
    name: 'Nintendo Switch OLED',
    description: 'Handheld gaming console with vibrant OLED display.',
    brand: 'Nintendo',
    model: 'Switch OLED',
    sku: 'HAC-001',
    categoryId: 'electronics',
    category: getCategoryById('electronics')!,
    images: [{ id: '1', url: '/product-10.jpg', thumbnail: '/product-10.jpg', alt: 'Switch OLED', type: 'main', order: 1 }],
    specifications: [{ attributeId: 'display', name: 'Display', value: '7" OLED', group: 'Display' }],
    attributes: { storage: '64GB', color: 'White', brand: 'Nintendo' },
    pricePoints: [
      { id: 'pp1', retailerId: 'amazon-us', retailer: getRetailer('amazon-us')!, price: 349, originalPrice: 349, currency: 'USD', availability: 'in_stock', condition: 'new', url: 'https://amazon.com/switch-oled', shippingCost: 0, shippingTime: '1-2 days', inStock: true, stockQuantity: 200, lastUpdated: new Date() },
      { id: 'pp2', retailerId: 'target', retailer: getRetailer('target')!, price: 349, originalPrice: 359, currency: 'USD', availability: 'in_stock', condition: 'new', url: 'https://target.com/switch-oled', shippingCost: 0, shippingTime: '2-3 days', inStock: true, stockQuantity: 150, discountPercent: 3, lastUpdated: new Date() },
    ],
    priceRange: { min: 349, max: 359, currency: 'USD' },
    rating: 4.8, reviewCount: 8500, availability: 'in_stock', condition: 'new',
    features: ['7" OLED Display', '64GB Storage', 'Handheld Mode'], tags: ['gaming', 'nintendo', 'switch'], isVerified: true, verifiedAt: new Date(),
    seo: { title: 'Nintendo Switch OLED - Compare Prices', description: 'Compare Switch OLED prices', keywords: ['nintendo', 'switch', 'gaming'] },
    createdAt: new Date('2021-10-01'), updatedAt: new Date(),
  },
  {
    id: '15',
    name: 'Dell XPS 15',
    description: 'Premium Windows laptop with stunning 4K display.',
    brand: 'Dell',
    model: 'XPS 15',
    sku: 'XPS-15-9530',
    categoryId: 'electronics',
    category: getCategoryById('electronics')!,
    images: [{ id: '1', url: '/product-3.jpg', thumbnail: '/product-3.jpg', alt: 'Dell XPS 15', type: 'main', order: 1 }],
    specifications: [{ attributeId: 'display', name: 'Display', value: '15.6" 4K', group: 'Display' }],
    attributes: { screen_size: 15.6, storage: '1TB', color: 'Silver', brand: 'Dell' },
    pricePoints: [
      { id: 'pp1', retailerId: 'amazon-us', retailer: getRetailer('amazon-us')!, price: 1899, originalPrice: 1999, currency: 'USD', availability: 'in_stock', condition: 'new', url: 'https://amazon.com/dell-xps-15', shippingCost: 0, shippingTime: '2-3 days', inStock: true, stockQuantity: 80, discountPercent: 5, lastUpdated: new Date() },
      { id: 'pp2', retailerId: 'bestbuy', retailer: getRetailer('bestbuy')!, price: 1849, originalPrice: 1999, currency: 'USD', availability: 'in_stock', condition: 'new', url: 'https://bestbuy.com/dell-xps-15', shippingCost: 0, shippingTime: 'Same day', inStock: true, stockQuantity: 40, discountPercent: 8, lastUpdated: new Date() },
    ],
    priceRange: { min: 1849, max: 1999, currency: 'USD' },
    rating: 4.7, reviewCount: 3200, availability: 'in_stock', condition: 'new',
    features: ['4K Display', 'Intel Core i7', '32GB RAM'], tags: ['laptop', 'dell', 'windows'], isVerified: true, verifiedAt: new Date(),
    seo: { title: 'Dell XPS 15 - Compare Prices', description: 'Compare Dell XPS 15 prices', keywords: ['dell', 'xps', 'laptop'] },
    createdAt: new Date('2023-08-01'), updatedAt: new Date(),
  },
  // Fashion
  {
    id: '16',
    name: 'Adidas Ultraboost 23',
    description: 'Premium running shoes with responsive Boost midsole.',
    brand: 'Adidas',
    model: 'Ultraboost 23',
    sku: 'GY8887',
    categoryId: 'fashion',
    category: getCategoryById('fashion')!,
    images: [{ id: '1', url: '/product-8.jpg', thumbnail: '/product-8.jpg', alt: 'Adidas Ultraboost', type: 'main', order: 1 }],
    specifications: [{ attributeId: 'midsole', name: 'Midsole', value: 'Boost', group: 'Comfort' }],
    attributes: { color: 'Core Black', brand: 'Adidas', size: '10' },
    pricePoints: [
      { id: 'pp1', retailerId: 'amazon-us', retailer: getRetailer('amazon-us')!, price: 190, originalPrice: 190, currency: 'USD', availability: 'in_stock', condition: 'new', url: 'https://amazon.com/adidas-ultraboost', shippingCost: 0, shippingTime: '1-2 days', inStock: true, stockQuantity: 500, lastUpdated: new Date() },
      { id: 'pp2', retailerId: 'nike', retailer: getRetailer('nike-store')!, price: 85, originalPrice: 100, currency: 'USD', availability: 'in_stock', condition: 'new', url: 'https://nike.com/ultraboost', shippingCost: 0, shippingTime: '3-5 days', inStock: true, stockQuantity: 300, discountPercent: 15, lastUpdated: new Date() },
    ],
    priceRange: { min: 85, max: 190, currency: 'USD' },
    rating: 4.6, reviewCount: 12000, availability: 'in_stock', condition: 'new',
    features: ['Boost midsole', 'Primeknit upper'], tags: ['shoes', 'adidas', 'running'], isVerified: true, verifiedAt: new Date(),
    seo: { title: 'Adidas Ultraboost 23 - Compare Prices', description: 'Compare Adidas Ultraboost prices', keywords: ['adidas', 'shoes', 'running'] },
    createdAt: new Date('2023-04-01'), updatedAt: new Date(),
  },
  {
    id: '17',
    name: 'Levi\'s 501 Original Fit Jeans',
    description: 'Classic straight-leg jeans for timeless style.',
    brand: "Levi's",
    model: '501',
    sku: '00501-1234',
    categoryId: 'fashion',
    category: getCategoryById('fashion')!,
    images: [{ id: '1', url: '/product-5.jpg', thumbnail: '/product-5.jpg', alt: "Levi's Jeans", type: 'main', order: 1 }],
    specifications: [{ attributeId: 'material', name: 'Material', value: '100% Cotton', group: 'Material' }],
    attributes: { color: 'Indigo', brand: "Levi's", size: '32' },
    pricePoints: [
      { id: 'pp1', retailerId: 'amazon-us', retailer: getRetailer('amazon-us')!, price: 69, originalPrice: 79, currency: 'USD', availability: 'in_stock', condition: 'new', url: 'https://amazon.com/levis-501', shippingCost: 0, shippingTime: '2-3 days', inStock: true, stockQuantity: 1000, discountPercent: 13, lastUpdated: new Date() },
      { id: 'pp2', retailerId: 'target', retailer: getRetailer('target')!, price: 59, originalPrice: 69, currency: 'USD', availability: 'in_stock', condition: 'new', url: 'https://target.com/levis-501', shippingCost: 0, shippingTime: '2-3 days', inStock: true, stockQuantity: 800, discountPercent: 14, lastUpdated: new Date() },
    ],
    priceRange: { min: 59, max: 79, currency: 'USD' },
    rating: 4.5, reviewCount: 25000, availability: 'in_stock', condition: 'new',
    features: ['100% Cotton', 'Classic fit', 'Button fly'], tags: ['jeans', 'levis', 'fashion'], isVerified: true, verifiedAt: new Date(),
    seo: { title: "Levi's 501 Jeans - Compare Prices", description: "Compare Levi's 501 prices", keywords: ['levis', 'jeans', 'fashion'] },
    createdAt: new Date('2020-01-01'), updatedAt: new Date(),
  },
  // Home Appliances
  {
    id: '18',
    name: 'Dyson V15 Detect',
    description: 'Powerful cordless vacuum with laser dust detection.',
    brand: 'Dyson',
    model: 'V15 Detect',
    sku: '374640-01',
    categoryId: 'appliances',
    category: getCategoryById('appliances')!,
    images: [{ id: '1', url: '/product-7.jpg', thumbnail: '/product-7.jpg', alt: 'Dyson V15', type: 'main', order: 1 }],
    specifications: [{ attributeId: 'battery', name: 'Battery', value: '60 minutes', group: 'Power' }],
    attributes: { color: 'Yellow', brand: 'Dyson' },
    pricePoints: [
      { id: 'pp1', retailerId: 'amazon-us', retailer: getRetailer('amazon-us')!, price: 749, originalPrice: 749, currency: 'USD', availability: 'in_stock', condition: 'new', url: 'https://amazon.com/dyson-v15', shippingCost: 0, shippingTime: '1-2 days', inStock: true, stockQuantity: 150, lastUpdated: new Date() },
      { id: 'pp2', retailerId: 'bestbuy', retailer: getRetailer('bestbuy')!, price: 699, originalPrice: 749, currency: 'USD', availability: 'in_stock', condition: 'new', url: 'https://bestbuy.com/dyson-v15', shippingCost: 0, shippingTime: 'Same day', inStock: true, stockQuantity: 80, discountPercent: 7, lastUpdated: new Date() },
      { id: 'pp3', retailerId: 'currys', retailer: getRetailer('currys')!, price: 599, originalPrice: 649, currency: 'GBP', availability: 'in_stock', condition: 'new', url: 'https://currys.com/dyson-v15', shippingCost: 0, shippingTime: '2-4 days', inStock: true, stockQuantity: 60, discountPercent: 8, lastUpdated: new Date() },
    ],
    priceRange: { min: 599, max: 749, currency: 'USD' },
    rating: 4.8, reviewCount: 7800, availability: 'in_stock', condition: 'new',
    features: ['Laser dust detection', 'HEPA filtration', '60min battery'], tags: ['vacuum', 'dyson', 'appliances'], isVerified: true, verifiedAt: new Date(),
    seo: { title: 'Dyson V15 Detect - Compare Prices', description: 'Compare Dyson V15 prices', keywords: ['dyson', 'vacuum', 'cordless'] },
    createdAt: new Date('2022-09-01'), updatedAt: new Date(),
  },
  {
    id: '19',
    name: 'Samsung Bespoke AI Oven',
    description: 'Smart oven with AI cooking technology.',
    brand: 'Samsung',
    model: 'Bespoke Oven',
    sku: 'NV90K9970',
    categoryId: 'appliances',
    category: getCategoryById('appliances')!,
    images: [{ id: '1', url: '/product-6.jpg', thumbnail: '/product-6.jpg', alt: 'Samsung Oven', type: 'main', order: 1 }],
    specifications: [{ attributeId: 'capacity', name: 'Capacity', value: '90L', group: 'Dimensions' }],
    attributes: { color: 'Glass White', brand: 'Samsung' },
    pricePoints: [
      { id: 'pp1', retailerId: 'homedepot', retailer: getRetailer('homedepot')!, price: 2499, originalPrice: 2799, currency: 'USD', availability: 'in_stock', condition: 'new', url: 'https://homedepot.com/samsung-oven', shippingCost: 0, shippingTime: '5-7 days', inStock: true, stockQuantity: 25, discountPercent: 11, lastUpdated: new Date() },
      { id: 'pp2', retailerId: 'lowes', retailer: getRetailer('lowes')!, price: 2399, originalPrice: 2699, currency: 'USD', availability: 'in_stock', condition: 'new', url: 'https://lowes.com/samsung-oven', shippingCost: 0, shippingTime: '3-5 days', inStock: true, stockQuantity: 20, discountPercent: 11, lastUpdated: new Date() },
    ],
    priceRange: { min: 2399, max: 2799, currency: 'USD' },
    rating: 4.6, reviewCount: 450, availability: 'in_stock', condition: 'new',
    features: ['AI Cooking', 'Smart Connectivity', '90L Capacity'], tags: ['oven', 'samsung', 'smart-home'], isVerified: true, verifiedAt: new Date(),
    seo: { title: 'Samsung Bespoke Oven - Compare Prices', description: 'Compare Samsung Oven prices', keywords: ['samsung', 'oven', 'smart'] },
    createdAt: new Date('2023-06-01'), updatedAt: new Date(),
  },
  // Beauty
  {
    id: '20',
    name: 'Dyson Supersonic Hair Dryer',
    description: 'Professional hair dryer with intelligent heat control.',
    brand: 'Dyson',
    model: 'Supersonic',
    sku: '375721-01',
    categoryId: 'beauty',
    category: getCategoryById('beauty')!,
    images: [{ id: '1', url: '/product-7.jpg', thumbnail: '/product-7.jpg', alt: 'Dyson Supersonic', type: 'main', order: 1 }],
    specifications: [{ attributeId: 'motor', name: 'Motor', value: 'V9 Digital', group: 'Performance' }],
    attributes: { color: 'Nickel/Fuchsia', brand: 'Dyson' },
    pricePoints: [
      { id: 'pp1', retailerId: 'sephora', retailer: getRetailer('sephora')!, price: 429, originalPrice: 479, currency: 'USD', availability: 'in_stock', condition: 'new', url: 'https://sephora.com/dyson-supersonic', shippingCost: 0, shippingTime: '2-3 days', inStock: true, stockQuantity: 200, discountPercent: 10, lastUpdated: new Date() },
      { id: 'pp2', retailerId: 'ulta', retailer: getRetailer('ulta')!, price: 399, originalPrice: 449, currency: 'USD', availability: 'in_stock', condition: 'new', url: 'https://ulta.com/dyson-supersonic', shippingCost: 0, shippingTime: '3-5 days', inStock: true, stockQuantity: 150, discountPercent: 11, lastUpdated: new Date() },
      { id: 'pp3', retailerId: 'amazon-uk', retailer: getRetailer('amazon-uk')!, price: 349, originalPrice: 379, currency: 'GBP', availability: 'in_stock', condition: 'new', url: 'https://amazon.co.uk/dyson-supersonic', shippingCost: 0, shippingTime: '2-4 days', inStock: true, stockQuantity: 100, discountPercent: 8, lastUpdated: new Date() },
    ],
    priceRange: { min: 349, max: 479, currency: 'USD' },
    rating: 4.7, reviewCount: 15000, availability: 'in_stock', condition: 'new',
    features: ['Intelligent heat control', 'V9 motor', '4 attachments'], tags: ['hair-dryer', 'dyson', 'beauty'], isVerified: true, verifiedAt: new Date(),
    seo: { title: 'Dyson Supersonic - Compare Prices', description: 'Compare Dyson Supersonic prices', keywords: ['dyson', 'hair-dryer', 'beauty'] },
    createdAt: new Date('2021-05-01'), updatedAt: new Date(),
  },
  // Sports
  {
    id: '21',
    name: 'Peloton Bike+',
    description: 'Premium indoor cycling bike with rotating HD touchscreen.',
    brand: 'Peloton',
    model: 'Bike+',
    sku: 'PLT-BIKE-PLUS',
    categoryId: 'sports',
    category: getCategoryById('sports')!,
    images: [{ id: '1', url: '/product-7.jpg', thumbnail: '/product-7.jpg', alt: 'Peloton Bike', type: 'main', order: 1 }],
    specifications: [{ attributeId: 'screen', name: 'Screen', value: '23.8" HD', group: 'Display' }],
    attributes: { color: 'Black', brand: 'Peloton' },
    pricePoints: [
      { id: 'pp1', retailerId: 'amazon-us', retailer: getRetailer('amazon-us')!, price: 2495, originalPrice: 2595, currency: 'USD', availability: 'in_stock', condition: 'new', url: 'https://amazon.com/peloton-bike-plus', shippingCost: 0, shippingTime: '5-7 days', inStock: true, stockQuantity: 50, discountPercent: 4, lastUpdated: new Date() },
      { id: 'pp2', retailerId: 'costco', retailer: getRetailer('costco')!, price: 2399, originalPrice: 2595, currency: 'USD', availability: 'in_stock', condition: 'new', url: 'https://costco.com/peloton-bike-plus', shippingCost: 0, shippingTime: '7-10 days', inStock: true, stockQuantity: 30, discountPercent: 8, lastUpdated: new Date() },
    ],
    priceRange: { min: 2399, max: 2595, currency: 'USD' },
    rating: 4.8, reviewCount: 8500, availability: 'in_stock', condition: 'new',
    features: ['Rotating HD screen', 'Auto-follow', 'Live classes'], tags: ['fitness', 'peloton', 'cycling'], isVerified: true, verifiedAt: new Date(),
    seo: { title: 'Peloton Bike+ - Compare Prices', description: 'Compare Peloton Bike+ prices', keywords: ['peloton', 'bike', 'fitness'] },
    createdAt: new Date('2022-03-01'), updatedAt: new Date(),
  },
  // Baby
  {
    id: '22',
    name: 'Baby Jogger City Mini GT2',
    description: 'All-terrain stroller with smooth ride.',
    brand: 'Baby Jogger',
    model: 'City Mini GT2',
    sku: 'BJ-2161425',
    categoryId: 'baby',
    category: getCategoryById('baby')!,
    images: [{ id: '1', url: '/product-7.jpg', thumbnail: '/product-7.jpg', alt: 'Stroller', type: 'main', order: 1 }],
    specifications: [{ attributeId: 'wheels', name: 'Wheels', value: '3" All-terrain', group: 'Wheels' }],
    attributes: { color: 'Graphite', brand: 'Baby Jogger' },
    pricePoints: [
      { id: 'pp1', retailerId: 'amazon-us', retailer: getRetailer('amazon-us')!, price: 299, originalPrice: 349, currency: 'USD', availability: 'in_stock', condition: 'new', url: 'https://amazon.com/baby-jogger-gt2', shippingCost: 0, shippingTime: '2-3 days', inStock: true, stockQuantity: 120, discountPercent: 14, lastUpdated: new Date() },
      { id: 'pp2', retailerId: 'buybuybaby', retailer: getRetailer('buybuybaby')!, price: 279, originalPrice: 329, currency: 'USD', availability: 'in_stock', condition: 'new', url: 'https://buybuybaby.com/baby-jogger-gt2', shippingCost: 0, shippingTime: '3-5 days', inStock: true, stockQuantity: 80, discountPercent: 15, lastUpdated: new Date() },
    ],
    priceRange: { min: 279, max: 349, currency: 'USD' },
    rating: 4.7, reviewCount: 2500, availability: 'in_stock', condition: 'new',
    features: ['All-terrain wheels', 'One-hand fold', 'UV 50+ canopy'], tags: ['stroller', 'baby', 'baby-jogger'], isVerified: true, verifiedAt: new Date(),
    seo: { title: 'Baby Jogger City Mini GT2 - Compare Prices', description: 'Compare stroller prices', keywords: ['stroller', 'baby', 'baby-jogger'] },
    createdAt: new Date('2021-06-01'), updatedAt: new Date(),
  },
  // Automotive
  {
    id: '23',
    name: 'Dash Cam 4K Ultra HD',
    description: 'High-resolution dash camera with night vision.',
    brand: 'Rexing',
    model: 'V1G-4K',
    sku: 'RX-V1G-4K',
    categoryId: 'automotive',
    category: getCategoryById('automotive')!,
    images: [{ id: '1', url: '/product-7.jpg', thumbnail: '/product-7.jpg', alt: 'Dash Cam', type: 'main', order: 1 }],
    specifications: [{ attributeId: 'resolution', name: 'Resolution', value: '4K Ultra HD', group: 'Video' }],
    attributes: { color: 'Black', brand: 'Rexing' },
    pricePoints: [
      { id: 'pp1', retailerId: 'amazon-us', retailer: getRetailer('amazon-us')!, price: 129, originalPrice: 159, currency: 'USD', availability: 'in_stock', condition: 'new', url: 'https://amazon.com/rexing-v1g', shippingCost: 0, shippingTime: '1-2 days', inStock: true, stockQuantity: 500, discountPercent: 19, lastUpdated: new Date() },
      { id: 'pp2', retailerId: 'autozone', retailer: getRetailer('autozone')!, price: 119, originalPrice: 149, currency: 'USD', availability: 'in_stock', condition: 'new', url: 'https://autozone.com/rexing-v1g', shippingCost: 0, shippingTime: '2-3 days', inStock: true, stockQuantity: 300, discountPercent: 20, lastUpdated: new Date() },
    ],
    priceRange: { min: 119, max: 159, currency: 'USD' },
    rating: 4.5, reviewCount: 8500, availability: 'in_stock', condition: 'new',
    features: ['4K Recording', 'Night Vision', 'WiFi'], tags: ['dash-cam', 'automotive', 'car-accessories'], isVerified: true, verifiedAt: new Date(),
    seo: { title: '4K Dash Cam - Compare Prices', description: 'Compare dash cam prices', keywords: ['dash-cam', 'car-camera', 'automotive'] },
    createdAt: new Date('2023-01-01'), updatedAt: new Date(),
  },
  // Health
  {
    id: '24',
    name: 'Fitbit Charge 6',
    description: 'Advanced fitness tracker with Google integration.',
    brand: 'Fitbit',
    model: 'Charge 6',
    sku: 'FB422CRBU',
    categoryId: 'health',
    category: getCategoryById('health')!,
    images: [{ id: '1', url: '/product-9.jpg', thumbnail: '/product-9.jpg', alt: 'Fitbit Charge 6', type: 'main', order: 1 }],
    specifications: [{ attributeId: 'battery', name: 'Battery', value: '7 days', group: 'Power' }],
    attributes: { color: 'Azure', brand: 'Fitbit' },
    pricePoints: [
      { id: 'pp1', retailerId: 'amazon-us', retailer: getRetailer('amazon-us')!, price: 159, originalPrice: 179, currency: 'USD', availability: 'in_stock', condition: 'new', url: 'https://amazon.com/fitbit-charge-6', shippingCost: 0, shippingTime: '1-2 days', inStock: true, stockQuantity: 800, discountPercent: 11, lastUpdated: new Date() },
      { id: 'pp2', retailerId: 'bestbuy', retailer: getRetailer('bestbuy')!, price: 149, originalPrice: 169, currency: 'USD', availability: 'in_stock', condition: 'new', url: 'https://bestbuy.com/fitbit-charge-6', shippingCost: 0, shippingTime: 'Same day', inStock: true, stockQuantity: 500, discountPercent: 12, lastUpdated: new Date() },
      { id: 'pp3', retailerId: 'amazon-uk', retailer: getRetailer('amazon-uk')!, price: 139, originalPrice: 159, currency: 'GBP', availability: 'in_stock', condition: 'new', url: 'https://amazon.co.uk/fitbit-charge-6', shippingCost: 0, shippingTime: '2-3 days', inStock: true, stockQuantity: 400, discountPercent: 13, lastUpdated: new Date() },
    ],
    priceRange: { min: 139, max: 179, currency: 'USD' },
    rating: 4.6, reviewCount: 12000, availability: 'in_stock', condition: 'new',
    features: ['GPS', 'Heart rate', 'Google apps'], tags: ['fitness-tracker', 'fitbit', 'health'], isVerified: true, verifiedAt: new Date(),
    seo: { title: 'Fitbit Charge 6 - Compare Prices', description: 'Compare Fitbit Charge 6 prices', keywords: ['fitbit', 'fitness-tracker', 'health'] },
    createdAt: new Date('2023-09-01'), updatedAt: new Date(),
  },
  // Books
  {
    id: '25',
    name: 'The Art of Problem Solving',
    description: 'Comprehensive math textbook for advanced students.',
    brand: 'AoPS',
    model: 'Vol 1 & 2',
    sku: '978-0977304585',
    categoryId: 'books',
    category: getCategoryById('books')!,
    images: [{ id: '1', url: '/product-5.jpg', thumbnail: '/product-5.jpg', alt: 'Math Book', type: 'main', order: 1 }],
    specifications: [{ attributeId: 'pages', name: 'Pages', value: '272', group: 'Details' }],
    attributes: { format: 'Paperback', brand: 'AoPS' },
    pricePoints: [
      { id: 'pp1', retailerId: 'amazon-books', retailer: getRetailer('amazon-books')!, price: 45, originalPrice: 55, currency: 'USD', availability: 'in_stock', condition: 'new', url: 'https://amazon.com/aops-book', shippingCost: 0, shippingTime: '2-3 days', inStock: true, stockQuantity: 1000, discountPercent: 18, lastUpdated: new Date() },
      { id: 'pp2', retailerId: 'barnes-noble', retailer: getRetailer('barnes-noble')!, price: 42, originalPrice: 52, currency: 'USD', availability: 'in_stock', condition: 'new', url: 'https://barnesandnoble.com/aops-book', shippingCost: 0, shippingTime: '3-5 days', inStock: true, stockQuantity: 500, discountPercent: 19, lastUpdated: new Date() },
    ],
    priceRange: { min: 42, max: 55, currency: 'USD' },
    rating: 4.8, reviewCount: 3500, availability: 'in_stock', condition: 'new',
    features: ['Comprehensive', 'Problem-solving', 'Math'], tags: ['book', 'math', 'education'], isVerified: true, verifiedAt: new Date(),
    seo: { title: 'Art of Problem Solving - Compare Prices', description: 'Compare book prices', keywords: ['book', 'math', 'education'] },
    createdAt: new Date('2019-01-01'), updatedAt: new Date(),
  },
];

export function getGlobalProducts(): Product[] {
  return GLOBAL_SAMPLE_PRODUCTS;
}
